### ISSUE TITLE
Did version 0.5 remove support for subfolders?

### ISSUE THREAD

**Issue by degerstrom** [tightenco/ziggy#102]
My Laravel installation is in a subfolder _/app/_ (which I can't change at this time), but support for this seems to have been removed in version 0.5?

I can verify that version 0.4 correctly accesses my routes at 

    /app/route/123

whereas version 0.5 removes the _/app/_ part and requests

    /route/123

Is this intentional, and if so is there a workaround?

**Comment by DanielCoulbourne** [comment]
This is definitely not intentional. I'll look into this

**Comment by DanielCoulbourne** [comment]
@degerstrom Can you shoot me a copy of the offending routes (including the route group with the namespace)?

**Comment by degerstrom** [comment]
@DanielCoulbourne Thanks for following up.

Here are my [0.4 routes](https://gist.github.com/degerstrom/174abb12c8b6466a04b20ddb8dd8de3b) and my [0.5 routes](https://gist.github.com/degerstrom/c7d9f7cc0f8e5a19e186a28605eb64b8).

**Comment by DanielCoulbourne** [comment]
@degerstrom sorry I meant from your Laravel routes file (so I can try to reproduce it locally)

(although what you provided IS helpful, thanks)
