### ISSUE TITLE
Problems with routes with '/' on its end

### ISSUE THREAD

**Issue by worldofswift** [tightenco/ziggy#106]
Good day.
Latest stable version of package, laravel 5.5.
How to reproduce:
Route::get('/surweys', 'SomeController@index')->name('surweys.index');
Route::get('/surweys/{surwey}', 'SomeController@show')->name('surweys.show');

So, if I type url localhost:8080/surweys and type in js console route().current(), it will show 'surweys.index' as expected, but if I go to localhost:8080/surweys/ - it predictably will be the same page as localhost:8080/surweys, but route().current() will give 'surweys.show', which is unexpected behaviour.

**Comment by worldofswift** [comment]
Stable I mean ^0.5.0

**Comment by DanielCoulbourne** [comment]
Whoops! This makes sense. I'll fix this bug tomorrow. 

Thanks for reporting it!
