### ISSUE TITLE
dingo/api Routing Support

### ISSUE THREAD

**Issue by bagaskarawg** [tightenco/ziggy#107]
Hi there,

First of all, thank you for this amazing stuff you guys made, it's working well as expected. But, I was creating a Single-page Application using Vue.js as the front-end and Laravel as the back-end.

Currently, I am using package named `dingo/api`(https://github.com/dingo/api/) for the API things. Unfortunately, while I was there, `dingo/api` uses its own Routing (`$api = app('Dingo\Api\Routing\Router');`) and therefore, all the routes registered with it is not displayed when I run the command `php artisan route:list` but it's displayed when I run `php artisan api:routes` which is coming with the package.

So, I wonder if ziggy can work together with dingo/api so every routes that's defined there will be 'exposed' to the javascript `route()` function. It will be a great help if it could, because I personally uses dingo/api for versioning, authentication, etc that's already available out-of-box.

Thank you.

**Comment by cristiancalara** [comment]
Hi @bagaskarawg 

I've had the same "issue". I've forked and implemented a quick way to send over additional routes via the routes directive. Basically I added a `$additionalRoutes` param that allows to send the routes over. I could submit a pull request if the package owners decides that this is a feature that they want to support.

For the code to get the routes in the format that Ziggy expects, I'm using:
```php
View::composer('partials.page.scripts', function ($view) {
    $api                = app('Dingo\Api\Routing\Router');
    $apiRoutes          = $api->getRoutes();
    $apiNameKeyedRoutes = collect([]);
    foreach ($apiRoutes as $version => $routesCollection) {
        $versionRoutes = collect($routesCollection->getRoutes());
        $versionNameKeyedRoutes = $versionRoutes
            ->filter(function ($route) {
                $action = $route->getAction();
                return $action && isset($action['as']) && $action['as'];
            })
            ->mapWithKeys(function ($route) use ($version) {
                $action = $route->getAction();
                $name   = $version . '.' . $action['as'];
                $data   = collect($route)->only(['uri', 'methods'])->put('domain', $route->domain());
                return [$name => $data];
            });
        $apiNameKeyedRoutes = $apiNameKeyedRoutes->merge($versionNameKeyedRoutes);
    }
    $view->with('apiZiggyRoutes', $apiNameKeyedRoutes);
});
```
And then I'm using the blade directive like: `@routes(false, $apiZiggyRoutes)`

**Comment by bagaskarawg** [comment]
hi @cristiancalara,

Wow, great! Thank you for sharing with us!

I've been thinking about extending the package directly too, but, in my idea it just needs to merge both, from Laravel's default `Routing` and Dingo's `Routing`, but, I see that your idea is quite good too.

Is there any way I could use your fork? I am not having an experience to install package from Git repository before, or maybe you have uploaded it to packagist maybe?

Thanks

**Comment by cristiancalara** [comment]
Hi @bagaskarawg 

I've looked a bit into having a more subtle merge of the routes, but nothing obvious showed up as the Dingo package extends on top of the Laravel routes, and they are not present as default Laravel routes.

Yes, you can temporarily add 

```json
"repositories":[  
   {  
      "type":"vcs",
      "url":"https://github.com/cristiancalara/ziggy"
   }
],
```

And update the require section - `tightenco/ziggy` to `dev-master@dev`
```json
"tightenco/ziggy": "dev-master@dev"
```

**Comment by bagaskarawg** [comment]
Thank you for your guidance, I will try it out later.

Just Sharing that I was thinking about changing method `nameKeyedRoutes()` from:

```
    protected function nameKeyedRoutes()
    {
        return collect($this->router->getRoutes()->getRoutesByName())
            ->map(function ($route) {
                if ($this->isListedAs($route, 'blacklist')) {
                    $this->appendRouteToList($route->getName(), 'blacklist');
                } elseif ($this->isListedAs($route, 'whitelist')) {
                    $this->appendRouteToList($route->getName(), 'whitelist');
                }
                return collect($route)->only(['uri', 'methods'])
                    ->put('domain', $route->domain());
            });
    }
```

into this:
```
    protected function nameKeyedRoutes()
    {
        $routes = collect();

        $routes->merge(
            collect($this->router->getRoutes()->getRoutesByName())
                ->map(function ($route) {
                    if ($this->isListedAs($route, 'blacklist')) {
                        $this->appendRouteToList($route->getName(), 'blacklist');
                    } elseif ($this->isListedAs($route, 'whitelist')) {
                        $this->appendRouteToList($route->getName(), 'whitelist');
                    }

                    return collect($route)->only(['uri', 'methods'])
                        ->put('domain', $route->domain());
            })
        );

        foreach($api->getRoutes() as $version => $router) {
            collect($router->getRoutes())->each(function ($route) use($routes, $version) {
                $routes->push(collect($route)->only(['uri', 'methods'])
                             ->put('domain', $route->domain())
                             ->put('version', $version));
            });
        }

        return $routes;
    }
```

But, maybe this needs to have a conditional clause to check if dingo is installed or not and maybe we could add an option in the config file or something like that.

**Comment by DanielCoulbourne** [comment]
If you guys want I'm totally open to making a configuration option to allow for you to provide your own Routes. We could pull `nameKeyedRoutes()` out into something like a `LaravelRouteCollector` class which would implement a `RouteCollector` interface. Then we could have a config option that would allow you to specify your own `RouteCollector` compliant `DingoRouteCollector` class.

Then @cristiancalara could publish his own package that was a Dingo adapter for Ziggy. That way down the road if anyone else is using a different system, they will be able to implement their own adapters.

In this case I think I favor making Ziggy extensible rather than trying to cram a bunch of new stuff into core to support Dingo.

What do you guys think of this?

**Comment by cristiancalara** [comment]
Yes, I also think extensible is the way to go and the approach you suggested sounds good. 

My concerns were about cluttering the documentation for this specific case e.g. if it's worth it. As:
- I don't really know any other packages that keep their routes separate from Laravel
- Dingo is currently in alpha release and there are chances that it may end up using the standard Laravel routes.

But I guess it's not a big effort to add this, and there may be other cases were a user may want to send over other custom routes so yeah, as you think.

**Comment by bagaskarawg** [comment]
Hi @DanielCoulbourne,

I think that way will make ziggy better and flexible which is great! That way we as user could be freely manage which adapter to be exposed to the javascript client.

As for me, I would love to see that implemented and I would like to contribute as much as I can to support ziggy in this feature.

And @cristiancalara, I too don't know any package that uses its own Route, but when the feature is implemented I guess there's no real problem because it just add flexibility to users which would help so much. And I don't think that dingo will user Laravel's default routing, because the default routing will need to be modified to reach it, but maybe it could be.

**Comment by DanielCoulbourne** [comment]
Okay great. I don't think I'll document the feature except with some comments I
In the code because I agree it will clutter the main docs.

**Comment by omadonex** [comment]
Hi, guys what you decided? I have the same "issue". I think that it a good way by making Ziggy extensible

**Comment by DanielCoulbourne** [comment]
I'm all for it but just haven't had the time to get around to it sorry. Hopefully next week!

**Comment by bagaskarawg** [comment]
Hi @DanielCoulbourne!

Great news! I have been waiting for this 👍 
Thank you for this and I have check it out for a while and will gladly help if needed.

**Comment by scheMeZa** [comment]
Awesome! Any updates on this? Would love to use it in my new project.

**Comment by DanielCoulbourne** [comment]
Yeah I have a PR open and I just havent tested it out yet.  @scheMeZa would you be willing to experiment with #149 and let me know how it feels to you?
