### ISSUE TITLE
Refactor ZiggyTokenBladeCompiler.

### ISSUE THREAD

**Issue by DanielCoulbourne** [tightenco/ziggy#11]

**Comment by jeffochoa** [comment]
@DanielCoulbourne in the [`ZiggiServiceProvider`](https://github.com/tightenco/ziggy/blob/master/src/BladeRouteGenerator.php) class you are including this line:

```php
use Tightenco\Ziggy\ZiggyTokenBladeCompiler;
```

Is this necessary ?

**Comment by mattstauffer** [comment]
@jeffochoa left over from the old structure. Dropped. Thanks!
