### ISSUE TITLE
nested objects for the request parameters

### ISSUE THREAD

**Issue by okmkey45** [tightenco/ziggy#112]
Hello. I am trying to add nested objects inside the url. For example, this is mi code:

```
let params = {
    advanced_filters: {
        name: 'Kyle',
        state: 'canceled'
    }
};
route('historic.data', params).toString();
```

and this returns:

```
http://agenda.test/historical-appointment/export?advancedFilter=[object Object],[object Object]
```

Does this mean that I can´t nest objects within other objects? or am I missing something?

Thanks for the help

**Comment by DanielCoulbourne** [comment]
Yeah. This is not Ziggy, this is just how URL params work.
