### ISSUE TITLE
Encode URLs?

### ISSUE THREAD

**Issue by reinink** [tightenco/ziggy#118]
I ran into a situation today where I was using user-generated input to generate URLs with Ziggy. For example:

```js
route('user.search', { ...my search params... })
```

However, if a user types in any character that has a special URL meaning (ie. an ampersand), then this URL is busted.

For example, if I search for "Jonathan&Amy", I'll get:

```
/users?search=Jonathan&Amy
```

Since the ampersand is a query string separator, my `search` value will only be "Jonathan".

A simple solution here would be to simply encode the URL when generating it using `encodeURIComponent()`. More info here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent.

**Comment by reinink** [comment]
Awesome, thanks @DanielCoulbourne!

**Comment by reinink** [comment]
@DanielCoulbourne I'm not sure what's wrong, but I'm not seeing the new `encodeURIComponent` stuff when I actually call `@routes`. Did we miss a step here? Maybe some build step?

![image](https://user-images.githubusercontent.com/882133/36261612-ee92233c-1232-11e8-8e03-c68be4bb98ee.png)

![image](https://user-images.githubusercontent.com/882133/36261618-f5ec2c04-1232-11e8-8fd8-a61d0644f6c9.png)

![image](https://user-images.githubusercontent.com/882133/36261644-0ac653ca-1233-11e8-8d02-562f94675fb4.png)

**Comment by DanielCoulbourne** [comment]
Oh that makes sense... I'll fix that in a few.

**Comment by avrahamappel** [comment]
Can we encode the keys as well as the values? So if I have
```
/fields[foo]=bar
```
it should become
```
/fields%5Bfoo%5D%3Dbar
```
