### ISSUE TITLE
Use Ziggy with browsersync proxy

### ISSUE THREAD

**Issue by vinjegaard** [tightenco/ziggy#125]
I've configured browsersync to proxy my application like this:
```
if (!mix.config.inProduction) {
    mix.browserSync({
        proxy: 'my-app.test:8000',
        open: false
    });
}
```

I run `npm run watch` for hot reloading and use the app from localhost:3000. If i send axios requests to '/api/foo' the request URL becomes 'localhost:300/api/foo' but if I use Ziggy ^0.6.0 it becomes 'my-app.test:8000/api/foo'. I went back to ^0.4.1 that does not change URL to app URL because Passport will not add laravel cookie and csrf headers and therefore all requests from Ziggy ^0.6.0 will return 401. 

I would like to use the most recent version of Ziggy but is it possible to get Ziggy to use localhost instead of app URL?

Thank you!

**Comment by DanielCoulbourne** [comment]
Yes! You could either not use absolute URLs in your dev environment, or you could modify your `APP_URL` in your .env

**Comment by vinjegaard** [comment]
Thank you for your reply @DanielCoulbourne! I've have changed APP_URL in .env, it does not change the Ziggy URL.

**Comment by DanielCoulbourne** [comment]
Try running `artisan view:clear` otherwise you can use the third param in the `route()` function to make the calls relative `route('post.show', {post: 1}, false)`

**Comment by vinjegaard** [comment]
view:clear didn't do anything but it did work by putting false as the third argument, I would however prefer to be able to change APP_URL instead as intended. I'm not sure why that doesn't work for me.

**Comment by glafarge** [comment]
The issue with CSRF, BrowserSync, and Inertia was resolved by adding the following code before all routes in the routes/web.php file :

```php
use Illuminate\Support\Facades\URL;

if (app()->environment('local') && !empty($app_url)) {
    // Parses app url and return its components
    $parsed_url = parse_url($app_url);

    // URL components
    $scheme = $parsed_url['scheme'] ?? '';
    $host = $parsed_url['host'] ?? '';
    $path = $parsed_url['path'] ?? '';

    // Rebuild URL with Browsersync port
    $root_url = $scheme.'://'.$host.':3000'.$path;

    // Force root url
    URL::forceRootUrl($root_url);
}
```

It's not required to activate relative links on js side afterwards.
Hope it helps
