### ISSUE TITLE
ziggy not included base url

### ISSUE THREAD

**Issue by ridwanskaterock** [tightenco/ziggy#126]
ziggy not included base url

like http://hostname/myproject/public/backend/blog/add

ziggy just retrive backend/blog/add 

*i not use php artisan serve for that 

if i use php artisan serve it's running 

how to setup it ? 

thanks

**Comment by manueldublanc** [comment]
I see that the fix is already in the master branch. The line 22 in `UrlBuilder.js` was missing in both builded scripts, even though it existed in the source files. Is it possible to tag this commit 77dce9f4a54000ebcf70b6bf5c619a8d99c33617 with v.0.6.1, so that it can be referenced with composer?

**Comment by jakebathman** [comment]
Until this gets tagged (I'll leave it up to @DanielCoulbourne to tag a release) you can require that commit in your project using:

`composer require tightenco/ziggy:dev-master#77dce9f`

**Comment by manueldublanc** [comment]
Yup, I wanted to do that, but I didn't like the idea to allow dev-branches in my composer json, so I installed the `composer-patches` package and added a patch. But luckily, @DanielCoulbourne already added the tag, so I don't have to worry about this anymore. Thanks!

**Comment by jakebathman** [comment]
Oh sweet, I didn't even check for that. I'll close this issue as resolved by v0.6.1
