### ISSUE TITLE
Route helper

### ISSUE THREAD

**Issue by fridzema** [tightenco/ziggy#128]
Hello, 

I can't live without this package anymore, should be in included in the core/scaffold of [laravel](https://github.com/laravel/laravel) if you ask me! 
But unfortunately i've had a lot of problems with conflicting packages in the past (https://github.com/tightenco/ziggy/issues/115). 
I would like to include this in my asset worflow so i don't have to use the blade directive anymore.

When i run `php artisan ziggy:generate` it generates a file including all my routes in `resources/assets/js/ziggy.js`. 

But my problem is that the route helper is not included in this file. 
I have tried getting the route helper from the vendor folder like this 
```js
.js(['resources/assets/js/ziggy.js', 'vendor/tightenco/ziggy/dist/js/route.js'], 'public/js/ziggy.js')
```

When i load the file it keeps saying route is not defined. 

Anybody here knows the proper way to achieve this?

**Comment by ankurk91** [comment]
`vendor/tightenco/ziggy/dist/js/route.js` file is trying to access `Ziggy` object and in your case `window.Ziggy` not available.
You may want to autoload `resources/assets/js/ziggy.js` file so that it is available to other modules without importing.

```js
mix.autoload([
 'resources/assets/js/ziggy.js': ['Ziggy', 'window.Ziggy']
])
```

**Comment by DanielCoulbourne** [comment]
@fridzema We also merged a PR recently that should fix the conflicts with other packages. Could you see if that fixes the issues you were having? It's tagged in 0.6.1

**Comment by fridzema** [comment]
@ankurk91 Thanks!
@DanielCoulbourne The issues are fixed! But i am always living on the edge and begin my day with updates (bad habit), and this package broke a lot of times. With a separate file this is no issue anymore and cleaner html output.
