### ISSUE TITLE
Documentation about querystrings.

### ISSUE THREAD

**Issue by Dawgora** [tightenco/ziggy#134]
Hello, I think the documentation should be updated, because of #34 . In the documentation there is nowhere to be written about the querystrings. I think it would be nice to add the code what Jesse wrote, or something similar.
for example:

```
var user = {id: 1, name: "John Doe", email: "john@example.com"};
var store = {id: 2, name: "example store"};

route('user.store.period',
                    {   user: user,
                            store: store,
                            country: null,
                            from: "2017-08-01",
                            till: "2017-09-01"},
                    );

//example.org/user/1/store/2/period?country=&from=2017-08-01&till=2017-09-01
```
I don't know exactly if the code what I wrote here is correct, but this just for example.

**Comment by DanielCoulbourne** [comment]
Great Idea! I'm planning to kill a bunch of issues next week during Tighten's onsite so I'll knock this out then.

**Comment by jakebathman** [comment]
One note: the example above from @Dawgora has a `null` value being rendered as `?country=`, when in the current codebase it'll be rendered literally, e.g.:

```js
route('foo', {bar: null, baz: 42});

// https://example.com/foo?bar=null&baz=42
```

It might be desirable to have `null` rendered as an empty value, but that'll require a future change.

**Comment by DanielCoulbourne** [comment]
@jakebathman how does laravel's`route()` handle it?

**Comment by jakebathman** [comment]
It excludes the key entirely:

```php
route('home', ["bar" => null, "baz" => 42]);

// https://ziggy-test.meow?baz=42
```

**Comment by DanielCoulbourne** [comment]
Ah. Well We should probably not pass in the string `null`
