### ISSUE TITLE
route helper return

### ISSUE THREAD

**Issue by erpfast** [tightenco/ziggy#135]
Hi there,

Just started using this and hoping to continue to do so. Really cool package.

I am using v 0.6.2 and the return from the route helper is a Router instance.
```
console.log(route('password.email'));
//Router {name: "password.email", absolute: undefined, numericParamIndices: true, urlParams: {…}, //queryParams: {…}}
```

From there I can access the router methods, but by the documentation it seems that it should be returning just the URI string? 

Thanks

**Comment by DanielCoulbourne** [comment]
You can get an explicit string with `.url()` but this object is string accessible so you’re good in most instances.
