### ISSUE TITLE
Explore building HTML docs from markdown programmatically.

### ISSUE THREAD

**Issue by DanielCoulbourne** [tightenco/ziggy#140]
### Expected Behavior
`npm run build` should generate updated HTML docs from the markdown docs.

**Comment by ankurk91** [comment]
Vue js community is heavily using 
https://www.gitbook.com

**Comment by jakebathman** [comment]
If we don't wanna move to a third-party thing like GitBook (which might be too much overhead for what's just a readme page), we'll have to re-structure the HTML file in the `gh-pages` branch. It's differently formatted enough to be frustrating.

Was the HTML generated from `.md` at some point, or coded by hand? Please say it was generated somewhere 🤞

**Comment by DanielCoulbourne** [comment]
Pretty sure the docs weren't programmatically generated. 

@the94air Can you confirm?

If they aren't I want to update it so that they are. This may require some major CSS updates.

**Comment by the94air** [comment]
No, it wasn't generated. I agree we should move to the automated version. I tried my best to make the HTML syntax as easy as it can in my last update of the docs by removing the sidebar (and also less CSS classes by relaying on tags only). I am using a stand alone version of Laravel mix and bootstrap 4 _so_ I am pretty sure any one of you can use it. Of course if you think that the md version is over kill then we can remove the HTML docs to make sure nothing get out of date.

**Comment by ankurk91** [comment]
What about `Jekyll`, GitHub has inbuilt support and it can convert MD files to html theme.
https://guides.github.com/features/pages/
