### ISSUE TITLE
Exclude query params where value is null

### ISSUE THREAD

**Issue by DanielCoulbourne** [tightenco/ziggy#141]
### Expected Behavior
```javascript
route('foo', {bar: null, baz: 42});

// https://example.com/foo?baz=42
```

### Current Behavior
```javascript
route('foo', {bar: null, baz: 42});

// https://example.com/foo?bar=null&baz=42
```

This was brought up in the comments for #134

**Comment by nunomaduro** [comment]
@DanielCoulbourne I believe that you may have introduced an unwanted behavior on this.

Previously:

```
route('foo', {bar: 0, baz: 42});

// https://example.com/foo?bar=0&baz=42
```

Now: 

```
route('foo', {bar: 0, baz: 42});

// https://example.com/foo&baz=42
```

Issue: The value `0` is ignored.

Want me to work on a pull request to fix this? 👍
