### ISSUE TITLE
Require laravel components to work with Lumen.

### ISSUE THREAD

**Issue by Lucassith** [tightenco/ziggy#145]
### Expected Behavior
Ability to work on Lumen with only a vital components of the whole framework.

### Current Behavior
Installing on Lumen will fail on dependency check.

Lumen is great for basic API application while using hardcoded routes is a _**pure evil**_ and it would be great if we all could use your work not only in full scale Laravel apps.

**Comment by DanielCoulbourne** [comment]
I would definitely merge a PR for this functionality, but I'm currently a little too busy to build out the necessary tests. Maybe this friday.

**Comment by DanielCoulbourne** [comment]
<img width="553" alt="screen shot 2018-04-13 at 9 53 00 pm" src="https://user-images.githubusercontent.com/429010/38763236-106cf400-3f65-11e8-9b12-21a3a291df9f.png">
<img width="420" alt="screen shot 2018-04-13 at 9 52 16 pm" src="https://user-images.githubusercontent.com/429010/38763237-1084972c-3f65-11e8-8f72-f2b23878fd00.png">


Seems to work for me?

**Comment by Lucassith** [comment]
Listing the Laravel catalog will show that there is also entire Laravel Framework alongside with Lumen Framework and this isn't correct.

**Comment by Lucassith** [comment]
Plus I tried to use ziggy by removing Laravel framework & orchestra (which also depends on whole framework) and I was convinced that it may not work due to Lumen's 'slimmer' router which does not contain Macro method.

**Comment by DanielCoulbourne** [comment]
I think of you want lumen support you might need to be the one to build it unfortunately. I think that’s out of scope for me right now but if you PR it I’ll gladly help test it.
