### ISSUE TITLE
Get pathname instead of full URL

### ISSUE THREAD

**Issue by jsgv** [tightenco/ziggy#146]
Is there any way to only retrieve the path of the link?

Instead of 
```js
console.log(url.url())
// http://mydomain.com/my/path/name
```
I want
```js
console.log(url.path())
// /my/path/name
```

Not sure if there is already a built in way to do this.

Or is it possible to disable `baseUrl`, `baseDomain`, etc from the generated JS file?
I basically only need everything after the domain.

Thanks

**Comment by DanielCoulbourne** [comment]
Yes, you can set absolute to false

https://github.com/tightenco/ziggy/blob/master/src/js/route.js#L128
