### ISSUE TITLE
Get full url

### ISSUE THREAD

**Issue by m1guelpf** [tightenco/ziggy#15]
Is there a way to get the full URL (like the Laravel helper does) instead of a relative URL (like this package does)?

**Comment by mattstauffer** [comment]
Good idea.

**Comment by mattstauffer** [comment]
I originally wrote a version that prepended baseUrl to all the links.

However, we have to consider this:

{username}.myapp.com

```javascript
route('user-dashboard', {username: mattstauffer})
```

**Comment by DanielCoulbourne** [comment]
I was able to solve @mattstauffer 's issue above using the super handy `$route->domain()` method on Route.php 😄 

Solved in #18
