### ISSUE TITLE
IE11 - Windows 7: Object doesn't support property or method 'assign'

### ISSUE THREAD

**Issue by MikeElghali** [tightenco/ziggy#150]
### Currently installed Laravel version:
`5.6.17`

### Currently installed Ziggy version
`0.6.3`

### Ziggy call in context

![capture d ecran 2018-04-19 a 10 26 03](https://user-images.githubusercontent.com/2301050/38980095-348ff43a-43bc-11e8-9dc4-f7ec2e0cc7ff.png)

**Comment by MarciBZA** [comment]
Also have the same issue, please fix

**Comment by OnlineMafia** [comment]
Please fix, the same issue!

**Comment by MikeElghali** [comment]
Hi,

I resolved my issue with a polyfill `es6-object-assign` (https://github.com/rubennorte/es6-object-assign).

Works very well with old browsers.

Regards.
