### ISSUE TITLE
Production @routes directive breaks tests that "assertSeeText()"

### ISSUE THREAD

**Issue by gmask** [tightenco/ziggy#155]
### Expected Behavior
Any tests that `assertSeeText()` and passed before should continue to pass regardless of Ziggy version.

### Current Behavior
Ziggy `0.6` breaks all tests that `assertSeeText()`

### Currently installed Laravel version:
`5.6.21`

### Currently installed Ziggy version
`0.6.6`

### The problem?
I think the reason this is breaking has to do with the minification that you guys now do, where `@routes` used to output this:

```
    (function webpackUniversalModuleDefinition(root, factory) {
    if(typeof exports === 'object' && typeof module === 'object')
        module.exports = factory();
    else if(typeof define === 'function' && define.amd)
        define("route", [], factory);
    else if(typeof exports === 'object')
        exports["route"] = factory();
    else
        root["route"] = factory();
})(this, function() {
return /******/ (function(modules) { // webpackBootstrap
/******/    // The module cache
/******/    var installedModules = {};
/******/
/******/    // The require function
/******/    function __webpack_require__(moduleId) {
/******/
/******/        // Check if module is in cache
/******/        if(installedModules[moduleId]) {
/******/            return installedModules[moduleId].exports;
/******/        }
```

It now looks like this:
```
!function(e,t){"object"==typeof exports&&"object"==typeof module?module.exports=t():"function"==typeof define&&define.amd?define("route",[],t):"object"==typeof exports?exports.route=t():e.route=t()}(this,function(){return function(e){function t(n){if(r[n])return r[n].exports;var o=r[n]={i:n,l:!1,exports:{}}
```

I totally prefer your newer approach, but do you know how to get it to play nice with Laravel's `seeText` type-tests?

**Comment by DanielCoulbourne** [comment]
What is the test that is failing?

**Comment by gmask** [comment]
PHPUnit tests that `assertSeeText()`:
```
/**
     * @test
     */
    public function the_customer_can_be_loaded()
    {
        $response = $this->get('/customers/view/123');

        $response->assertStatus(200)
            ->assertSeeText('Customer 123')
            ->assertSeeText('Concord, NC');
    }
```

**Comment by DanielCoulbourne** [comment]
Wait seriously? This makes no sense. I'll play with it in the next day or so and see if i can debug.

**Comment by gmask** [comment]
I decided to keep looking at this and re-setup my testing environment and re-clone the project. After this I can't get the code generated by `@routes` to minify, so the tests are working. I'm on `0.6.6` still but for some reason the blade directive is only generating the long-form JS. Not sure what's going on lol.

**Comment by DanielCoulbourne** [comment]
But you're saying the assertSeeText tests fail even if the text they are seeing is unrelated to ziggy?

**Comment by gmask** [comment]
The `assertSeeText` tests fail if Ziggy is in production/minified mode. If in testing mode the tests pass. I'm not sure if this is an issue with Ziggy or Laravel or even PHPUnit, Ziggy is just triggering the failure.

**Comment by gmask** [comment]
Adding another piece of the puzzle: switching my `assertSeeText` calls to `assertSee` allows the tests to pass, regardless of `APP_ENV`'s value.

`assertSeeText` breaks under these `APP_ENV` values:
* `dev`
* `testing`
* `production`

And it works under these:
* `local`

**Comment by DanielCoulbourne** [comment]
I have not been able to duplicate this one yet. Gonna close this for now, until I get someone else with the same issue.

**Comment by gmask** [comment]
@DanielCoulbourne 

It's fairly simple to reproduce:

* Create new Laravel app
* Pull in Ziggy
* Add your `app.js` and `app.css` files to the `welcome.blade.php` view
* Add your `@routes` call to the head of the `welcome.blade.php` view
* Create the following test:
```
    /**
     * @test
     */
    public function ziggy_breaks_tests_that_assertSeeText()
    {
        $response = $this->get('/');

        $response->assertSee("Laravel")
            ->assertSee("Documentation")
            ->assertSee("Laracasts")
            ->assertSee("News")
            ->assertSee("Nova")
            ->assertSee("Forge")
            ->assertSee("GitHub");
    }
```
* It will pass, now change all of the `assertSee` to `assertSeeText`. It will fail.
* Remove the `@routes` directive from the `welcome` view's head. The tests with `assertSeeText` will pass.

**Comment by DanielCoulbourne** [comment]
<img width="2559" alt="screen shot 2018-08-28 at 1 55 24 pm" src="https://user-images.githubusercontent.com/429010/44741066-0ba0bf80-aaca-11e8-9aa6-d895dadfa349.png">

**Comment by DanielCoulbourne** [comment]
This is in Laravel 5.4 (an installation I had lying around. I'll double check that it's the same in stable later today)

**Comment by gmask** [comment]
Wow... when I move the `@routes` to the very top of `<head>` like in your screenshot the tests pass again... move yours to just before the closing `</head>` tag and see if it fails?

**Comment by gmask** [comment]
Docs say:
```
3. Include our Blade Directive (@routes) somewhere in your template before your main application JavaScript is loaded—likely in the header somewhere.
```

However, moving `@routes` to the bottom of the page, just before my main app.js file, does indeed fix it. I guess I'll keep it that way rofl.

Thanks for the troubleshooting.

**Comment by DanielCoulbourne** [comment]
Super weird

**Comment by JacobBennett** [comment]
FYI, just had same problem. Fixed it by moving `@routes` to footer.
