### ISSUE TITLE
Generating typescript definitions?

### ISSUE THREAD

**Issue by hailwood** [tightenco/ziggy#156]
Hey @DanielCoulbourne,

I'm going to be working on automatically generating typescript definitions, the awesome thing about this is that for us typescript users we'll be able to know the shape of the params object based off the route name and get alerted of any errors instantly. See below.

Anyway, my question is, would you merge this in, or should I work on creating my own package as an extension of Ziggy?

It would be an entirely optional secondary command e.g. you'd call

```bash
php artisan ziggy:generate "resources/routes.js"
php artisan ziggy:typescript "resources/types/routes.d.ts"
```

It would have no effect on the `@routes` blade directive.

![image](https://user-images.githubusercontent.com/709773/41003414-d1dc511a-696a-11e8-8a03-f7ed1aa61396.png)

Cheers,
Matt

**Comment by DanielCoulbourne** [comment]
Gonna close this issue for now. Feel free to keep working on it or reopen

**Comment by iDevelopThings** [comment]
Sorry to dig up an old thread, I just hacked something together, it could maybe be created as a PR and merged in by somebody else :)

I picked some pieces of current stuff and slapped them together in a way that works nicely.

First of all, yarn add @types/ziggy-js

Create a new laravel console command; I basically ripped the current ziggy:generate command and updated it to work with ts

```
<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Filesystem\Filesystem;
use Tightenco\Ziggy\Ziggy;

class ZiggyTsDefinitionsCommand extends Command
{
    protected $signature = 'ziggy:ts-definitions';

    protected $description = 'Generate TS definitions for ziggy';

    protected $files;

    public function __construct(Filesystem $files)
    {
        parent::__construct();

        $this->files = $files;
    }

    public function handle()
    {
        $path            = './resources/ts/shims-ziggy.d.ts';
        $generatedRoutes = $this->generate();

        $this->makeDirectory($path);
        $this->files->put(base_path($path), $generatedRoutes);

        $this->info('File generated!');
    }

    private function generate(): string
    {
        $ziggy  = (new Ziggy(false, null));
        $routes = collect($ziggy->toArray()['routes'])
            ->map(function ($route, $key) {
                $methods = json_encode($route['methods'] ?? []);

                return <<<TYPESCRIPT
    "{$key}": {
        "uri": "{$route['uri']}",
        "methods": {$methods}
    },
TYPESCRIPT;

            })
            ->join("\n");

        return <<<TYPESCRIPT

import {Config, InputParams, Router} from "ziggy-js";

type LaravelRoutes = {
    {$routes}
    [key: string]: string;
}

declare global {
    declare interface ZiggyLaravelRoutes extends LaravelRoutes {}
    declare function route(): Router;
    declare function route(name: keyof ZiggyLaravelRoutes, params?: InputParams, absolute?: boolean, customZiggy?: Config): string;
}

export { LaravelRoutes };

TYPESCRIPT;
    }

    protected function makeDirectory($path)
    {
        if (!$this->files->isDirectory(dirname(base_path($path)))) {
            $this->files->makeDirectory(dirname(base_path($path)), 0755, true, true);
        }

        return $path;
    }
}```

Create a laravel mix extension to automatically generate the definitions when changing routes/compiling - also ripped the one that's already documented

```
const mix    = require('laravel-mix');
const {exec} = require('child_process');

mix.extend('ziggy', new class {
    register(config = {})
    {
        this.watch   = config.watch ?? ['routes/**/*.php'];
        this.enabled = config.enabled ?? !Mix.inProduction();
    }

    boot()
    {
        if (!this.enabled) return;

        const command = () => exec(
            `php artisan ziggy:ts-definitions`,
            (error, stdout, stderr) => console.log(stdout)
        );

        command();

        if (Mix.isWatching() && this.watch) {
            ((require('chokidar')).watch(this.watch))
                .on('change', (path) => {
                    console.log(`${path} changed...`);
                    command();
                });
        }
    }
}());

```

In webpack.mix.js

```
mix
    .js('resources/ts/app.ts', 'public/js')
    .vue({
        version : 3,
    })
    **.ziggy()**
```

Now... when you build, this shims-ziggy.d.ts file will be generated with the following content:

```
import {Config, InputParams, Router} from "ziggy-js";

type LaravelRoutes = {
        "login": {
        "uri": "login",
        "methods": ["GET","HEAD"]
    },
    "logout": {
        "uri": "logout",
        "methods": ["POST"]
    },
    "password.request": {
        "uri": "forgot-password",
        "methods": ["GET","HEAD"]
    },
    "password.reset": {
        "uri": "reset-password/{token}",
        "methods": ["GET","HEAD"]
    },
    "password.email": {
        "uri": "forgot-password",
        "methods": ["POST"]
    },
    "password.update": {
        "uri": "reset-password",
        "methods": ["POST"]
    },
    "register": {
        "uri": "register",
        "methods": ["GET","HEAD"]
    },
    "user-profile-information.update": {
        "uri": "user/profile-information",
        "methods": ["PUT"]
    },
    "user-password.update": {
        "uri": "user/password",
        "methods": ["PUT"]
    },
    "password.confirm": {
        "uri": "user/confirm-password",
        "methods": ["GET","HEAD"]
    },
    "password.confirmation": {
        "uri": "user/confirmed-password-status",
        "methods": ["GET","HEAD"]
    },
    "two-factor.login": {
        "uri": "two-factor-challenge",
        "methods": ["GET","HEAD"]
    },
    "two-factor.enable": {
        "uri": "user/two-factor-authentication",
        "methods": ["POST"]
    },
    "two-factor.disable": {
        "uri": "user/two-factor-authentication",
        "methods": ["DELETE"]
    },
    "two-factor.qr-code": {
        "uri": "user/two-factor-qr-code",
        "methods": ["GET","HEAD"]
    },
    "two-factor.recovery-codes": {
        "uri": "user/two-factor-recovery-codes",
        "methods": ["GET","HEAD"]
    },
    "terms.show": {
        "uri": "terms-of-service",
        "methods": ["GET","HEAD"]
    },
    "policy.show": {
        "uri": "privacy-policy",
        "methods": ["GET","HEAD"]
    },
    "profile.show": {
        "uri": "user/profile",
        "methods": ["GET","HEAD"]
    },
    "other-browser-sessions.destroy": {
        "uri": "user/other-browser-sessions",
        "methods": ["DELETE"]
    },
    "current-user-photo.destroy": {
        "uri": "user/profile-photo",
        "methods": ["DELETE"]
    },
    "current-user.destroy": {
        "uri": "user",
        "methods": ["DELETE"]
    },
    "api-tokens.index": {
        "uri": "user/api-tokens",
        "methods": ["GET","HEAD"]
    },
    "api-tokens.store": {
        "uri": "user/api-tokens",
        "methods": ["POST"]
    },
    "api-tokens.update": {
        "uri": "user/api-tokens/{token}",
        "methods": ["PUT"]
    },
    "api-tokens.destroy": {
        "uri": "user/api-tokens/{token}",
        "methods": ["DELETE"]
    },
    "bot.backtesting.show": {
        "uri": "bot/backtesting",
        "methods": ["GET","HEAD"]
    },
    "bot.backtesting.start": {
        "uri": "bot/backtesting",
        "methods": ["POST"]
    },
    "dashboard": {
        "uri": "dashboard",
        "methods": ["GET","HEAD"]
    },
    [key: string]: string;
}

declare global {
    declare interface ZiggyLaravelRoutes extends LaravelRoutes {}
    declare function route(): Router;
    declare function route(name: keyof ZiggyLaravelRoutes, params?: InputParams, absolute?: boolean, customZiggy?: Config): string;
}

export { LaravelRoutes };

```

Boom :D 
![image](https://user-images.githubusercontent.com/4105581/123638768-71cc6480-d817-11eb-832d-b1d1d676c6ca.png)

**Comment by francislavoie** [comment]
@iDevelopThings That's amazing! Thank you!

A few minor adjustments to avoid some TS errors:

```php
        return <<<TYPESCRIPT

            import {Config, InputParams, Router} from "ziggy-js";

            type LaravelRoutes = {
                [key: string]: { uri: string, methods: string[] };
            {$routes}
            }

            declare global {
                interface ZiggyLaravelRoutes extends LaravelRoutes {}
                function route(): Router;
                function route(name: keyof ZiggyLaravelRoutes, params?: InputParams, absolute?: boolean, customZiggy?: Config): string;
            }

            export { LaravelRoutes };

            TYPESCRIPT;
```

- Use the routes type `[key: string]: { uri: string, methods: string[] };` which is more correct than `[key: string]: string;`

- Remove `declare` from each item inside of `declare global`, which gives error `TS1038: A 'declare' modifier cannot be used in an already ambient context.`, it's essentially redundant since `declare global` already says `declare`.

- Untab `{$routes}` by one step which makes it aligned properly in the output (avoids the double indentation)

- Tab in the heredoc (which is possible since PHP 7.3, see https://wiki.php.net/rfc/flexible_heredoc_nowdoc_syntaxes)

**Comment by cjholowatyj** [comment]
Damn it would be great to create something like this for Vite now that it is gaining widespread adoption as a de-facto default across new Laravel applications...
