### ISSUE TITLE
Add ability to exclude routes

### ISSUE THREAD

**Issue by svenluijten** [tightenco/ziggy#16]
Let's say I have some super secret endpoints (`/admin/whatever`), I'd like to be able to exclude them from the routes that are exposed via the generated JSON.

Maybe this can be achieved by adding a middleware, like how [`aaronlord/laroute`](https://github.com/aaronlord/laroute) does it. 

As an extension of this, it'd be neat if I could use route groups to only expose certain routes to a "named" group, so I could use `@routes('admin')` in my blade file(s) to only expose routes in the `admin` group.

**Comment by DanielCoulbourne** [comment]
I've been doing some thinking along these lines as well.

**Comment by mikemand** [comment]
I dislike the way `laroute` does this since I have to go through and blacklist any routes I don't want to be visible, and if I forget to blacklist a route...

I would much rather have to whitelist the specific routes (or a route group). I also like your idea of using the directive to only expose routes, but I wonder if it would be possible to make it so they have to fit a specific pattern (`admin.*` or `api.v1.*`)?

**Comment by ctf0** [comment]
i think i can make a PR for this as i was just thinking of the same thing

**Comment by DanielCoulbourne** [comment]
@mikemand I was initially planning to export by default and require a blacklist. Can you think of any situations where accidentally exposing a route would cause a serious issue? I don't see it as a security issue so far, but happy to be proven wrong.

I think I'm okay with using a whitelist, but I'd prefer to use groups. Let me do a little thinking on this before you start working on a PR @ctf0, I may want to do something with macroing Router or something. If you have any specific plans for implementation let me know :)

**Comment by ctf0** [comment]
@DanielCoulbourne actually the PR is already made 😆 .

regarding the route group, i dont think laravel exposes this info through the `router->getRoutes()` however here is a way around if u r interested https://github.com/ctf0/pretty-routes/blob/master/views/routes.blade.php#L41-L51

**Comment by DanielCoulbourne** [comment]
@ctf0 I made a few comments on the PR. In general I'd like to keep to one major change per PR. I would have loved to merge parts of it but not the whole thing. More info in my review of #17 

Thanks for being willing to write the code! Let's work together to get it merged 😄

**Comment by mikemand** [comment]
@DanielCoulbourne I cannot really think of anything, security-wise. Any serious API should have ways to prevent DoS attacks and the like, but this doesn't just expose API routes; it exposes all of them.

I couldn't imagine ever needing to expose the password reset routes and any administrative support routes probably shouldn't be exposed either. This is more personal preference, though, I guess.

**Comment by DanielCoulbourne** [comment]
@mikemand and @ctf0 

Okay I have a compromise for you guys. I don't like publishing a config file by default, but I don't mind having an optional config file.

What if we publish all routes by default, then add support for optional `config('ziggy.whitelist')` and `config('ziggy.blacklist')` settings.

That way average users who don't care won't have to worry about black/white-listing routes, but if someone wants to do that, they have the option of just creating a `config/ziggy.php` file and adding one of those settings?

I'm thinking the setting could be an array of regular expressions, i.e. - 

```php
$whitelist = [
    /^auth./,
    /bank.vault/
];
```

This way it would be relatively simple to target entire route namespaces, or "any `delete` endpoint" or whatever.

How does that sit with y'all?

**Comment by mikemand** [comment]
That sounds great to me. 👍

**Comment by DanielCoulbourne** [comment]
Sweet! I'll try to get it implemented this weekend, unless someone beats me to the PR 🥇 😄

**Comment by JesseLeite** [comment]
It might be cool to be able to add multiple groups of regexes as well.  For example, maybe your app has 3 different user roles:

- Admins (has access to all routes)
- Authors (has access to author and guest routes only)
- Guests (has access to guest routes only)

Furthermore, imagine you have 3 master layout files for each role (one for admin dashboard, one for author dashboard, and another for all guest pages).  It would be cool to be able to specify regex groups for all three master layouts:

```php
'groups' => [
    'admin' => [
        /.*/,
    ],
    'author' => [
        ^(?!admin\.).*,
    ],
    'guest' => [
        ^(?!admin\.)(?!author\.).*
    ]
]
```

Then `@routes` would return all routes, and `@routes('author')` would return the `author` regexed group of routes for the author dashboard, etc.  Thoughts?

**Comment by ctf0** [comment]
@JesseLeite a simpler approach would be adding a filter on the route groups like [laroute](https://github.com/aaronlord/laroute#ignorefilter-routes), and a middleware to check the filter and generate the js routes accordingly.

**Comment by JesseLeite** [comment]
@ctf0 ah interesting.  I like that implementation as well!

I have to say though, I work on one application where we have hundreds of routes.  A regex in a config might be a lot simpler for us, though obviously not as granular as laroute's implementation.  Curious where Ziggy will go with this :)

**Comment by mattstauffer** [comment]
In case y'all weren't thinking this, I'd consider using Laravel's regex matcher that allows for shortcuts like "api.*"" -- the thing that is sourced by "Str::is"

**Comment by stevebauman** [comment]
Definitely looking forward to this, as I'm only looking to expose my API endpoints in JavaScript.

Just a suggestion instead of a config file, there's also the option of actually calling upon a `Ziggy` class and a static function in our `AppServiceProvider`? As an example:

```php
public function register()
{
    Ziggy::only('api.*');
}
```

**Comment by DanielCoulbourne** [comment]
Thanks for the input all. At this point I am implementing the [optional config version](https://github.com/tightenco/ziggy/issues/16#issuecomment-321930652) of this feature with the option to support [Laravel's nice string wildcards](https://github.com/laravel/framework/blob/5.4/src/Illuminate/Support/Str.php#L141).

Once this is implemented we can talk about extending the functionality with these other ideas. Just so you have a sense of my general vibe towards each:
 - **Groups**: I'd probably merge this if someone built it
 - **Middleware based whitelisting and blacklisting**: I don't love it. I think I would be a lot more friendly toward a Router.php macro as an option for whitelisting in the routes file.
 - **Custom registration**: I don't really know about this. Makes me a little nervous. I'd like to hear about how you would implement it.
