### ISSUE TITLE
Weird caching error

### ISSUE THREAD

**Issue by sunscreem** [tightenco/ziggy#163]
### Expected Behavior
I'm using ziggy on several projects no problems at all.

### Current Behavior
I'm unable to replicate the issues that some users seem to be having. I'm only aware of it because the javascript errors are being reported in bugsnag. Seems some users aren't able to 'see' some routes I recently added. When I look at the stack track on bugsnag, indeed the new routes are missing. But when I view source the routes are there.

![image](https://user-images.githubusercontent.com/7523595/42957591-11873a50-8b7b-11e8-8adf-cebe166b7006.png)

Screen cap from bugsnag

Now - when you look at the namedRoutes in bugsnag, indeed the new routes are missing:

```
namedRoutes: {"home":{"uri":"\/","methods":["GET","HEAD"],"domain":null},"bars.hasBeer":{"uri":"bar-has-beer\/{beer}","methods":["GET","HEAD"],"domain":null},"beers.index":{"uri":"beers","methods":["GET","HEAD"],"domain":null},"beers.create":{"uri":"beers\/create","methods":["GET","HEAD"],"domain":null},"beers.store":{"uri":"beers","methods":["POST"],"domain":null},"beers.show":{"uri":"beers\/{beer}","methods":["GET","HEAD"],"domain":null},"beers.edit":{"uri":"beers\/{beer}\/edit","methods":["GET","HEAD"],"domain":null},"beers.update":{"uri":"beers\/{beer}","methods":["PUT","PATCH"],"domain":null},"beers.destroy":{"uri":"beers\/{beer}","methods":["DELETE"],"domain":null}},
```

### Currently installed Laravel version:
`5.6.26`

### Currently installed Ziggy version
`0.6.6`

### Example route from your Laravel Routes file.
```php
Route::get('/system-status', 'SystemStatusController@index')->name('system.status');
```
### Contents of Ziggy.namedRoutes
```
bars.hasBeer
:
{uri: "bar-has-beer/{beer}", methods: Array(2), domain: null}
beers.create
:
{uri: "beers/create", methods: Array(2), domain: null}
beers.destroy
:
{uri: "beers/{beer}", methods: Array(1), domain: null}
beers.edit
:
{uri: "beers/{beer}/edit", methods: Array(2), domain: null}
beers.index
:
{uri: "beers", methods: Array(2), domain: null}
beers.show
:
{uri: "beers/{beer}", methods: Array(2), domain: null}
beers.store
:
{uri: "beers", methods: Array(1), domain: null}
beers.update
:
{uri: "beers/{beer}", methods: Array(2), domain: null}
home
:
{uri: "/", methods: Array(2), domain: null}
system.status
:
{uri: "system-status", methods: Array(2), domain: null}
```

### Ziggy call in context
```javascript
 axios.get(route('system.status'))
```

Live site causing the issues: https://dogpubtimemachine.com/
Code for this site (all OS): https://github.com/sunscreem/dogpubtimemachine

**Comment by DanielCoulbourne** [comment]
Great bug report.

Are you using the blade directive to load your routes or are you using the artisan call?

**Comment by sunscreem** [comment]
I'm using the blade directive :)

https://github.com/sunscreem/dogpubtimemachine/blob/0858a7c98105e189e59fe26ffe58d0b3eac26776/resources/views/layouts/partials/head-tags-and-scripts.blade.php#L10

**Comment by sunscreem** [comment]
Closing this as the bug hasn't been seen again for 4 days now so, whatever was causing it seems to have gone away. Very odd.
