### ISSUE TITLE
[Question/Feature] Whitelist by group or group prefix

### ISSUE THREAD

**Issue by OwenMelbz** [tightenco/ziggy#164]
### Expected Behavior
By default, laravel gives you route files which some have prefixes, such as `api/`.

It also automatically generates names for you via helpers such as `Route::apiResource`

The whitelist should potentially allow you to control by group level, e.g I want to include only "api" routes.

Currently the whitelist/blacklist seems to only allow filtering via the actual route names, rather than the route groups.

### Current Behavior
Either I don't know how to do to this, or it seems you need to then manually overwrite every API route in your application to prefix the name with `api.` to allow you to only export IP routes.

**Comment by DanielCoulbourne** [comment]
That is correct. Unfortunately laravel route groups are ephemeral and it is impossible to retreive routes by group. The simple solution to this is to wrap your entire `api.php` routes file in a group with a name, such as 
```Route::group(['as => 'api.'], function ($router) {
    //
});```
