### ISSUE TITLE
Feature Request: Appending routes

### ISSUE THREAD

**Issue by hubertnnn** [tightenco/ziggy#165]
I can see a few situations where allowing multiple calls to @routes would be useful.
For example when I have a lot of shared routes for everyone and a few for just admins.

Here is an example config file:

    return [
        'whitelist' => [
            'api.*',
        ],
        'groups' => [
            'admin' => [
                'admin.*',
            ],
        ],
    ];

And blade directives:

    @routes()
    @routes('admin')

I would expect this to load both `api.*` and `admin.*` routes instead of just loading the last command used.
This will be especially helpful, when the main routes are generated using `artisan ziggy:generate` command and the admin routes are only added in admin panel for users that are already logged in.

**Comment by DanielCoulbourne** [comment]
Great Idea. I'd accept a PR for this.
