### ISSUE TITLE
Support Laravel 5.7 please

### ISSUE THREAD

**Issue by zablockijj** [tightenco/ziggy#167]
### Expected Behavior
Let me upgrade to Laravel 5.7

### Current Behavior
Can't

### Currently installed Laravel version:
`5.6.24`

### Currently installed Ziggy version
`0.6.0`

**Comment by benallfree** [comment]
#168

**Comment by ankurk91** [comment]
Should be fixed by
https://github.com/tightenco/ziggy/pull/170

**Comment by DanielCoulbourne** [comment]
Not tagged yet. I want to do further testing tomorrow, but you can install dev-master as of today and be fine I think

**Comment by DanielCoulbourne** [comment]
tagged
