### ISSUE TITLE
Compatibility with Laravely 5.5 and below projects

### ISSUE THREAD

**Issue by tnorthcutt** [tightenco/ziggy#169]
Looks like [this commit](https://github.com/tightenco/ziggy/commit/4bc6e6a3e4146a0b4691b4a583074ed82959c654) removed <= 5.5 compatibility. Any particular reason why, @DanielCoulbourne? I see that `orchestra/testbench` requires Laravel 5.7, but since that's only a dev requirement for Ziggy, is there a compelling reason to not let 5.5 projects use Ziggy?

### Expected Behavior
I attempted to install Ziggy with `composer require tightenco/ziggy`, and expected it to install in my Laravel 5.5 project.

### Current Behavior
Composer installation fails, because Ziggy requires Laravel `^5.6.7`

### Currently installed Laravel version:
`5.5.40`

### Currently installed Ziggy version
N/A

**Comment by DanielCoulbourne** [comment]
There is not a good reason not to support 5.5 (even 5.4 should be fine) but I’m pretty tied up this week so if you felt compelled to make a PR I’d love that 😎👌👌🍪
