### ISSUE TITLE
Optional route parameters results in a default http:// protocol rewrite, even with force https on.

### ISSUE THREAD

**Issue by Owchzzz** [tightenco/ziggy#172]
### Expected Behavior
_If this is a new feature, give a usage example._
when calling a route via ziggy that has an optional parameter, it should return the string. for example `route('test.number',{number:'123'})`
Should return something like
`https://app.com/test/123`

# However
### Current Behavior
It returns 
`http://app.com/test/123`

### Currently installed Laravel version:
`5.5.28`

### Currently installed Ziggy version
`0.6.0`

### Example route from your Laravel Routes file.
_i.e. -_
```php
Route::get('/venues/{venue}', 'VenuesController@show')->name('venues.show');
```
### Contents of Ziggy.namedRoutes
_In dev tools type `Ziggy.namedRoutes` and copy the result here._

### Ziggy call in context
_i.e. –_
```javascript
// Api client is a wrapper around Axios
axios.get(route('api.utilities.formatNumber',{number: this.callData.MOBILE_NUMBER})).then((resp) => {
                console.log('Response to number formatter:',resp);
                this.activeNumber = resp.data.formattedNumber;

                this.browserCallingActive = true;

            });
```

**Comment by tnorthcutt** [comment]
I haven't been able to reproduce this, unfortunately. @Owchzzz is this still occurring for you?
