### ISSUE TITLE
Optional route parameters leads to redundant trailing slashes

### ISSUE THREAD

**Issue by asologor** [tightenco/ziggy#174]
I have such route:
```php
Route::get('/{section?}/{sub_section?}/{anything?}', 'AdmController@index')
    ->where([
        'section'     => '[\w\-_]+',
        'sub_section' => '[\w\-_]+',
        'anything'    => '.*',
    ])
    ->name('admin.home');
```

`AdmController@index` method signature:
```php
public function index($section = 'some-string', $sub_section = null, $anything = null)
```

Then I call `route('admin.home', ['first']).url()` on the back-end and on the front-end sides.

Back-end result:  http://admin.mydomain.local/first
Front-end result: http://admin.mydomain.local/first//

### Expected Behavior
Front-end `route()` function produces the same result as the back-end `route()` function

### Current Behavior
`route()` function adds two trailing slashes to the end of the produced url

### Currently installed Laravel version:
`5.6.35`

### Currently installed Ziggy version
`v0.6.8.1`

### Example route from your Laravel Routes file.
```php
Route::get('/{section?}/{sub_section?}/{anything?}', 'AdmController@index')
    ->where([
        'section'     => '[\w\-_]+',
        'sub_section' => '[\w\-_]+',
        'anything'    => '.*',
    ])
    ->name('admin.home');
```
### Contents of Ziggy.namedRoutes
```
{
  admin.home:
    domain: "admin.mydomain.local"
    methods: (2) ["GET", "HEAD"]
    uri: "{section?}/{sub_section?}/{anything?}"
    __proto__: Object
}
```

### Ziggy call in context
```javascript
window.route(...)
```

**Comment by asologor** [comment]
As a temp fix I managed to decorate `url()` method and trim all trailing slashes:
```js
const _route = window.route;

window.route = function () {
  const routeInstance = _route.apply(window, arguments);
  const _url = routeInstance.url;
  
  routeInstance.url = function () {
    return _url.call(routeInstance).replace(/\/+$/, '');
  };

  return routeInstance;
};
```

**Comment by ankurk91** [comment]
Laravel 5.7

```php
Route::get('/dashboard/{one?}/{two?}', 'DashboardController')->name('dashboard');
```
```php
route('dashboard');
// https://example.test/dashboard
route('dashboard',1);
// https://example.test/dashboard/1
route('dashboard',[1, 2]);
// https://example.test/dashboard/1/2
route('dashboard',['one'=> 1, 'two'=> 2]);
// https://example.test/dashboard/1/2


route('dashboard',['two'=> 2]);
// https://example.test/dashboard//2
```

Notice the last one, it has double slashes, even Laravel does not care if you missed one of optional parameter.

**Comment by DanielCoulbourne** [comment]
Fair point @ankurk91. If laravel changes their helper method we'll change ours to match, but for now I'll close this

**Comment by asologor** [comment]
@ankurk91 In your second example (without named params) Laravel does not produce trailing slashes:
```
route('dashboard',1);
// https://example.test/dashboard/1
```
but ziggy does:
```
// https://example.test/dashboard/1/
```

Add more optional params and you'll see more slashes.

**Comment by ankurk91** [comment]
@asologor 
I agree.

You have already suggested a solution above. Why don't you come up a PR with tests.

It is Hacktoberfest 2018 going on 😄

**Comment by asologor** [comment]
@ankurk91

No-no-no :smile: Sorry, but I have not enough time for contributing now.
