### ISSUE TITLE
Add relativeUrl() function

### ISSUE THREAD

**Issue by Livijn** [tightenco/ziggy#176]
Add `relativeUrl()` function so you can get the relative path for the named route. Useful i.e. like this:

```
new VueRouter({
            mode: 'history',
            base: route('messages.index').relativeUrl(),
            routes: [
                {
                    name: 'conversation',
                    path: '/:id',
                    component: Conversation,
                }
            ]
        })
```

**Comment by DanielCoulbourne** [comment]
Path relative to `route().current()` I assume?

**Comment by Livijn** [comment]
I was actually going for relative to root.

**Comment by mattisbones** [comment]
In your case would calling `route('messages.index', [], false).url()` to strip the domain work?

**Comment by Livijn** [comment]
Yes, that seems to do the trick. I am just replacing it like this `route('messages.index').replace(Ziggy.baseUrl, '')`, which is to me, more readable. 

Maybe a `route().withoutDomain()` would be good?
