### ISSUE TITLE
CSP support

### ISSUE THREAD

**Issue by Jannick94** [tightenco/ziggy#181]
### Expected Behavior
Being able to specify either a nonce or a hash for my CSP policy. Which is then inserted into the script tag generated by Ziggy.

### Current Behavior
The "template" from which the DOM is generated is just a static HEREDOC notated string. Which causes my CSP policy to block the resulting script tag.
 https://github.com/tightenco/ziggy/blob/master/src/BladeRouteGenerator.php#L39-L50

### Currently installed Laravel version:
`5.5.28`

### Currently installed Ziggy version
`0.6.0`

**Comment by ankurk91** [comment]
You can completely disable the `@route` directive and use the command to generate the routes to a separate js file

https://github.com/tightenco/ziggy/blob/master/src/CommandRouteGenerator.php#L13

**Comment by DanielCoulbourne** [comment]
If you make a PR that allows you to do this without adding a parameter to the blade directive, I'd merge it.

As long as it doesn't change the surface-level userland api or make BladeRouteGenerator too complicated, I'm good with whatever.

The other options are to :

1) do what @ankurk91 suggests above
2) extend BladeRouteGenerator and make it output the script tag the way you want, then add your own blade directive
