### ISSUE TITLE
JS current method with optional parameter

### ISSUE THREAD

**Issue by s-widerberg** [tightenco/ziggy#191]
### Expected Behavior
When the URI you are currently navigated to uses an optional parameter route().current() should return the current route

### Current Behavior
When I'm on a route with an optional parameter, and am not using the optional parameter, route().current() is returning undefined. If I use the parameter route().current() is working correctly.

In the route listed below when I'm on

```/quotes/futures```
```route().current()``` -> undefined

```/quotes/futures/```
```route().current()``` -> undefined

```/quotes/futures/something```
```route().current()``` -> quotes.futures as expected

### Currently installed Laravel version:
`5.6.16`

### Currently installed Ziggy version
`0.6.9`

### Example route from your Laravel Routes file.
_i.e. -_
```php
Route::get('quotes/futures/{symbol?}', 'FuturesController@index')->name('quotes.futures');
```
### Contents of Ziggy.namedRoutes
```js
{"quotes.futures":{"uri":"quotes/futures/{symbol?}","methods":["GET","HEAD"],"domain":null}}
```

**Comment by Livijn** [comment]
I am experiencing the same bug.
