### ISSUE TITLE
Parameter behavior changed

### ISSUE THREAD

**Issue by codegain** [tightenco/ziggy#192]
The behavior of handling optional parameters has changed from Ziggy 0.6.2 to 0.6.8 (I could not install any version in-between because of laravel version constraint) and the newest version is not working for me.
It always takes the "id" query parameter as route-parameter which it didn't do in my previous installed version (0.6.2). Do I have to change some configuration to make this work again?

### Expected Behavior
In chrome dev-tools:
```
> route('myRoute', { bookId: 1819, id: 123456 }).toString()
"https://my.site/data/1819/text?id=123456"
> route('myRoute', { bookId: 1819 }).toString()
"https://my.site/data/1819/text"
```
(with Ziggy 0.6.2)

### Current Behavior
In chrome dev-tools:
```
> route('myRoute', { bookId: 1819, id: 123456 }).toString()
"https://my.site/data/123456/text"
> route('myRoute', { bookId: 1819 }).toString()
"https://my.site/data/1819/text"
```
(since Ziggy 0.6.8)

### Currently installed Laravel version:
`5.5.44`

### Currently installed Ziggy version
`0.6.9`

### Example route from your Laravel Routes file.
```php
Route::group(array('prefix' => 'data'), function () {
    Route::group(array('prefix' => '{bookId}'), function() {
        Route::post('text', array('as' => 'myRoute', 'uses' => 'TextController@createSave'));
    });
});
```

**Comment by codegain** [comment]
**Ziggy 0.6.2:**
```
> route('myRoute', { bookId: 1819, id: 123456 })
	Router {name: "myRoute", absolute: undefined, numericParamIndices: false, urlParams: {…}, queryParams: {…}}
	absolute: undefined
	name: "myRoute"
	numericParamIndices: false
	queryParams: {bookId: 1819, id: 123456}
	urlParams: {bookId: 1819, id: 123456}
	__proto__: String
```

**Ziggy 0.6.8:**
```
> route('myRoute', { bookId: 1819, id: 123456 })
	Router {name: "myRoute", absolute: undefined, ziggy: {…}, template: "https://my.site/data/{bookId}/text", numericParamIndices: true, …}
	absolute: undefined
	name: "myRoute"
	numericParamIndices: true
	queryParams: {0: 123456}
	template: "https://my.site/data/{bookId}/text"
	urlParams: {0: 123456}
	ziggy: {namedRoutes: {…}, baseUrl: "https://my.site/", baseProtocol: "https", baseDomain: "my.site", basePort: false, …}
	__proto__: String
```

**Comment by DanielCoulbourne** [comment]
Heads up, I've been working on debugging this for a few hours. Its very annoying, but a fix should be coming soon

**Comment by bakerkretzmar** [comment]
Pretty sure this is because as of `0.6.7` we're specifically looking for an `id` key on the object passed in:

https://github.com/tightenco/ziggy/blob/master/src/js/route.js#L24-L34
