### ISSUE TITLE
laravel 5.7 new resource folder structure

### ISSUE THREAD

**Issue by suabahasa** [tightenco/ziggy#194]
### Expected Behavior
when we run ziggy:generate command, the js file is created in resource folder.
the resource path for laravel 5.7 have been changed and remove "assets" subfolder as written on 
https://laravel.com/docs/5.7/upgrade#upgrade-5.7.0

### Currently installed Laravel version:
`5.7`

I think this line https://github.com/tightenco/ziggy/blob/cb6baff5563cf719c6a3f194382da7bdc2c8f1db/src/CommandRouteGenerator.php#L13
should be changed to
    `protected $signature = 'ziggy:generate {path=./resources/js/ziggy.js} {--url=/}';`

I'm sorry for my English

**Comment by SimplyThomas** [comment]
This needs to detect what version of Laravel and set the path accordingly.

Also, Laravel 5.7 does not force this flattened folder structure, so it would really need to do more detection than just version to be as accurate as possible (or allow a .env override?).

**Comment by fridzema** [comment]
You can provide a path of the output file:
```bash
php artisan ziggy:generate --help
Description:
  Generate js file for including in build process

Usage:
  ziggy:generate [options] [--] [<path>]

Arguments:
  path                   [default: "./resources/assets/js/ziggy.js"]
```

**Comment by DanielCoulbourne** [comment]
If someone wants to PR a way of auto-detecting laravel version and setting the path automagically, I'd merge it. Otherwise, there is an option to set it manually as @fridzema noted.
