### ISSUE TITLE
Using @routes results in: Uncaught ReferenceError: Ziggy is not defined

### ISSUE THREAD

**Issue by robfrancken** [tightenco/ziggy#195]
### Currently installed Laravel version:
`5.6.39`

### Currently installed Ziggy version
`0.6.9`

I've included the @routes directive in the header of my template.

Here is the output in the header. 

```javascript
<script type="text/javascript">
    (function() {
var routes = {"api.mailgun.cases.test":{"uri":"api\/mailgun\/cases\/test","methods":["GET","HEAD"],"domain":null}};

        for (var name in routes) {
            Ziggy.namedRoutes[name] = routes[name];
        }
    })();
</script>
```

**Comment by robfrancken** [comment]
Perhaps a file got corrupted during install. Reinstalled the project and it works seamlessly now.

**Comment by notflip** [comment]
What do you mean with "reinstalled the project", I'm having the same issue, already ran compoer install and npm install

**Comment by robfrancken** [comment]
Deleted ./vendor and ./node_modules directories then `composer install` and `npm install`. That resolved the issue for me.

**Comment by notflip** [comment]
I think I might be confused by which javascript has to be inluded as well, is it enough to have
`import route from 'ziggy`
Or do we have to import the main library as well?

**Comment by robfrancken** [comment]
`import route from 'ziggy'` only imports the helper function.

If you've generated the routes file with artisan command, e.g. `php artisan ziggy:generate "resources/js/ziggy"`, you'll need to import that file as well.

To use the route helper function, you need to make the generated routes accessible. I've just bound to the window object below, but you can import it into your Vue components as described in the docs if your prefer.

```
// resources/js/app.js

import route from 'ziggy'
import { Ziggy } from './ziggy'

window.Ziggy = Ziggy;

console.log('route', route);
console.log('Ziggy', Ziggy);
console.log('test', route('blog.index'));
```

Hopefully that clears things up for you!

**Comment by notflip** [comment]
Perfect! That solves it for me, thank you!
