### ISSUE TITLE
Passing parameter catch with javascript to route

### ISSUE THREAD

**Issue by vijaymgr** [tightenco/ziggy#197]
Thank you for this awesome package. I am unable to pass parameter to named route. 

For example:
Route:
I have route resource as
`Route::resource('user', 'UserController');`

 I passed id from html and catch with javascript: and want to pass the id with route whitle updating and deleting. 
```
<script>
var id = $(this).data('id');

something like:
var route = route('user.destroy', {id: id}); //id is not working
</script>
```
How can I do that using this package?

**Comment by jes490** [comment]
You should pass it as `route('user.destroy', { user: id })`

**Comment by vijaymgr** [comment]
.@jes490 it's not working

**Comment by DanielCoulbourne** [comment]
What do you mean it's "not working"?

What is the result?
