### ISSUE TITLE
route().current() not working for base route

### ISSUE THREAD

**Issue by reinink** [tightenco/ziggy#200]
I have a dashboard route defined in Laravel:

```php
Route::get('/')->name('dashboard')->uses('DashboardController@index');
```

But when I call `route().current()` on the dashboard page (`/`), this function returns undefined.

I would have expected `dashboard`.

**Comment by andrewgorpenko** [comment]
Confirmed, same is happening to me.

**Comment by DanielCoulbourne** [comment]
Thanks for this. Sorry for slow replies on all the recent issues. Haven't had a ton of 20% time lately. Hopefully this weekend or next week

**Comment by object505** [comment]
I got the same issue. In Ziggy.namedRoutes object I can see the route name:
`home: {uri: "/", methods: Array(2), domain: null}` but when using `route().current()` I get undefined.
Any plans when this will be fixed?

**Comment by maxxscho** [comment]
Same here - base route isn't working with `route().current()`. I guess something with the trailing slash?

**Comment by DanielCoulbourne** [comment]
This should be fixed in the latest build, which I'll tag today. 
<img width="700" alt="Screen Shot 2019-04-26 at 5 47 31 PM" src="https://user-images.githubusercontent.com/429010/56838286-74a02900-684b-11e9-833a-a22907c9c5ee.png">

**Comment by reinink** [comment]
Thanks @DanielCoulbourne!

**Comment by maxxscho** [comment]
Works like a charm. Thank you @DanielCoulbourne !
