### ISSUE TITLE
Inconsistency in query param with array value

### ISSUE THREAD

**Issue by karkowg** [tightenco/ziggy#202]
Given a route with a query param key that has an array as a value
`route('route', ['foo' => ['a', 'b', 'c']])`

Laravel's route helper returns `/route?foo[0]=a&foo[1]=b&foo[2]=c` while ziggy returns `/route?foo=a,b,c`. When getting the param from the request object it handles it as a string and not an array.

### Currently installed Laravel version:
`5.7.*`

### Currently installed Ziggy version
`0.6.0`

**Comment by curtisblackwell** [comment]
Is there any reason #219 hasn't been accepted yet? Just busyness?

In case it's helpful, I copied the changes locally and confirmed URLs are generated as I expected.

**Comment by bakerkretzmar** [comment]
Closed by #228.
