### ISSUE TITLE
Laravel Mix Url for Production server

### ISSUE THREAD

**Issue by rpsimao** [tightenco/ziggy#205]
I've generated the _ziggy.js_ file from the artisan `ziggy:generate`

I'm using the file with _Laravel Mix_, but the problem is that the url generated is from the dev server.

I have this in my _app.js_ file, for overwriting:
```javascript
import {Ziggy} from './ziggy';
import route from '../../../vendor/tightenco/ziggy/src/js/route';

window.Ziggy = Ziggy;

Ziggy.baseUrl = location.protocol+'//'+location.hostname;
Ziggy.baseProtocol = location.protocol;
Ziggy.baseDomain = location.hostname;
```
Is this the correct way, or is there another way to change the url for production?

**Comment by aaronhuisinga** [comment]
This is actually a really interesting problem now while using Laravel Vapor. It generates a vanity URL for the app, which when using Ziggy and using a generated file, will not work.

**Comment by jakebathman** [comment]
If either of you could get us some reproducible configs (like a route definition and example `ziggy:generate` output) we can take a look. I'm not sure if the solution is closer to a bug fix or a feature for some kind of dynamic base URL fixer as provided by @rpsimao.

**Comment by rpsimao** [comment]
I've been using my solution for every project I need. So for it has been working flawlesssly.

A new project I'm working this are my files:

**Custom route file (routes/internal.php)**
```php
Route::whitelist()->get('/reserva/{id}', 'InternalRoutesController@getReservaForStore')->name('internal.get.reserva.by.id');

Route::group(['prefix' => 'avantio'], function(){
    Route::whitelist()->get('/reserva/{id}', 'AvantioApiController@getReservaById')->name('internal.avantio.get.reserva.by.id');
});
```

**Ziggy Generated File (php artisan ziggy:generate)**
```js
    var Ziggy = {
        namedRoutes: {"internal.get.reserva.by.id":{"uri":"internal\/reserva\/{id}","methods":["GET","HEAD"],"domain":null},"internal.avantio.get.reserva.by.id":{"uri":"internal\/avantio\/reserva\/{id}","methods":["GET","HEAD"],"domain":null}},
        baseUrl: 'http://lvreservas.test/',
        baseProtocol: 'http',
        baseDomain: 'lvreservas.test',
        basePort: false,
        defaultParameters: []
    };

    if (typeof window.Ziggy !== 'undefined') {
        for (var name in window.Ziggy.namedRoutes) {
            Ziggy.namedRoutes[name] = window.Ziggy.namedRoutes[name];
        }
    }

    export {
        Ziggy
    }
```

**App.js (/resources/assests/js/app.js)**

...
```js
import { Ziggy } from './routes';
import route from '../../../vendor/tightenco/ziggy/src/js/route';

window.Ziggy = Ziggy;

Ziggy.baseUrl = location.protocol+'//'+location.hostname;
Ziggy.baseProtocol = location.protocol;
Ziggy.baseDomain = location.hostname;

window.route = route;
```

**Comment by bakerkretzmar** [comment]
@rpsimao we'll look into supporting this in the future, but for now, you can set the environment variable for the app URL when running the command to generate the routes file:

```sh
APP_URL=https://your-production-domain.biz php artisan ziggy:generate
```

This will generate the routes file using `https://your-production-domain.biz` or whatever URL you pass into it.
