### ISSUE TITLE
Cannot use id param for query strings

### ISSUE THREAD

**Issue by dbpolito** [tightenco/ziggy#206]
I got a route with no param declared, and i'm using like this:

```
route('something', {type: 'a', id: 1});
```

* Current: `/something?0=1`
* Expected: `something?type=a&id=1`

Probably introduced by https://github.com/tightenco/ziggy/pull/143

**Comment by jakebathman** [comment]
Can anyone reproduce this? I'll give it a try this Friday if not, just to see if it's still a bug and if it is we'll get a fix in.

**Comment by JameL83** [comment]
I can reproduce this and i think its this function normalizeParams in routes.js, correct me if i am wrong.

    normalizeParams(params) {
	if (typeof params === 'undefined')
            return {};

        // If you passed in a string or integer, wrap it in an array
        params = typeof params !== 'object' ? [params] : params;

        // If the tags object contains an ID and there isn't an ID param in the
        // url template, they probably passed in a single model object and we should
        // wrap this in an array. This could be slightly dangerous and I want to find
        // a better solution for this rare case.

        if (params.hasOwnProperty('id') && this.template.indexOf('{id}') == -1) {
            params = [params.id];
        }

        this.numericParamIndices = Array.isArray(params);
        return Object.assign({}, params);
    }

**Comment by JameL83** [comment]
Any progress on this?

**Comment by KuNman** [comment]
I confirm this behavior.

Debug result of `route(url, {page: 1, id: 2})`. 
Get params are broken.

**Comment by hydrogennz** [comment]
@KuNman did the route you were building this for have an optional id param?

i.e. `Route::get("/check/{id?}")->name("check")`

The issue I think is the check in `normalizeParams` needs to also check for optional ID params.

e.g.:
```js
        if (
            params.hasOwnProperty('id') && this.template.indexOf('{id}') == -1
        ) {
            params = [params.id];
        }
```
needs to be:

```js
        if (
            params.hasOwnProperty('id') &&
            (this.template.indexOf('{id}') == -1 && this.template.indexOf('{id?}') == -1)
        ) {
            params = [params.id];
        }
```
