### ISSUE TITLE
typeError: route is not a function

### ISSUE THREAD

**Issue by CptMisery** [tightenco/ziggy#217]
### Expected Behavior
Should be able to add `@routes` to my blade and then the `route` function in JS should get routes

### Current Behavior
The JS gives me this error: 
typeError: route is not a function

Note: I did get this working by adding `()` after `@routes`. However, after loading just one page with that change, I could then remove the `()` and everything continued to work. I did clear my cache (browser and artisan) between each test.

### Currently installed Laravel version:
5.5.28

### Currently installed Ziggy version
0.7.1

**Comment by DanielCoulbourne** [comment]
Did you clear your view cache as well as the laravel cache?

**Comment by zhanang19** [comment]
Try `php artisan view:clear` and `php artisan config:clear` if you use an advanced config

**Comment by amrikasir** [comment]
or, try to clear caches in your browser. sometimes I got this error too.

try to check the code the browser render, Ctrl + U. `@routes` just add a tag `<script>...</script>`.
