### ISSUE TITLE
route().current() returning 'undefined' for form POST routes

### ISSUE THREAD

**Issue by kcchurch** [tightenco/ziggy#218]
Hello - first off, great package, thanks so much!

I have encountered an issue where the **current** route value for POST routes always comes back 'undefined'.  This does not happen for my GET routes, including when I change an undefined POST route into a GET route for testing purposes.  I can also change a working GET route to POST and it always returns undefined.  These routes are all defined in my web.php file using the 'web' middleware grouping.

I also tried adding one of my POST routes to the array of excluded URIs in VerifyCsrfToken in case it was a glaring CSRF token issue, but that did not change any behavior.

### Expected Behavior
`route().current()` should provide me with the name of my POST routes, as it does for GET routes.

### Current Behavior
`route().current()` returns 'undefined' for POST routes.

### Currently installed Laravel version:
5.4.36

### Currently installed Ziggy version
0.7.1

### Example route from your Laravel Routes file.
_i.e. -_
```php
Route::post('studySetup', 'PathologyController@studySetup')->name('studySetup');
```
### Contents of Ziggy.namedRoutes
```
assignStudies: {uri: "assignStudies", methods: Array(2), domain: null}
checkInOut: {uri: "/", methods: Array(2), domain: null}
debugbar.assets.css: {uri: "_debugbar/assets/stylesheets", methods: Array(2), domain: null}
debugbar.assets.js: {uri: "_debugbar/assets/javascript", methods: Array(2), domain: null}
debugbar.clockwork: {uri: "_debugbar/clockwork/{id}", methods: Array(2), domain: null}
debugbar.openhandler: {uri: "_debugbar/open", methods: Array(2), domain: null}
dev_connections: {uri: "dev/connections", methods: Array(2), domain: null}
downloadTables: {uri: "downloadTables", methods: Array(2), domain: null}
globalChanges: {uri: "globalChanges", methods: Array(2), domain: null}
importStudies: {uri: "importStudies", methods: Array(2), domain: null}
managePermissions: {uri: "managePermissions", methods: Array(2), domain: null}
ntpPathologistReview: {uri: "ntpPathologistReview", methods: Array(2), domain: null}
previousChanges: {uri: "previousChanges", methods: Array(2), domain: null}
qaPathologistReview: {uri: "qaPathologistReview", methods: Array(2), domain: null}
selectionCriteria: {uri: "selectionCriteria", methods: Array(1), domain: null}
standardAnimalSelection: {uri: "standardAnimalSelection", methods: Array(2), domain: null}
studySetup: {uri: "studySetup", methods: Array(1), domain: null}
updateCheckInOutData: {uri: "updateCheckInOutData/{study_number}", methods: Array(2), domain: null}
__proto__: Object
```

### Ziggy call in context
_i.e. –_
```javascript
$(document).ready(function() {
... 
    // Page-specific document ready functionality
    switch (route().current()) {
        case 'studySetup':
            console.log("Hooray, we made it to studySetup!");
            break;
        default:
            console.log("Not studySetup - route.current() = " + route().current());
            break;
    }
});
```

**Comment by thoresuenert** [comment]
@kcchurch maybe we faced a similar problem today:

First of all, `POST` routes are not visitable, i cannot stay on those routes from a user perspective.
So i makes no sense to me.

We had following problem in our `routes` files:

```
Route::get('studySetup', 'PathologyController@studySetup')->name('studySetup');
Route::post('studySetup', 'PathologyController@studySetup')->name('studySetup');
```

Because both routes share the same name, there should be a conflict somewhere in the current check or namedRoutes building blocks.

The `get route` gets removed in `current` checks and will end in `undefined`.

when you change the routes to the following, everything works for us as aspected:
```
Route::get('studySetup', 'PathologyController@studySetup')->name('studySetup');
Route::post('studySetup', 'PathologyController@studySetup')->name('studySetup.update');
```

I have to investigate more, or a documentation is needed for that part.
Laravel itself does not prevent me from using the same names.

**Comment by kcchurch** [comment]
Hi @thoresuenert - thanks for the response.

I have confirmed that I do not have any duplicate route names in web.php, so that is not the issue.

I am surprised that you had duplicated route names with matching GET/POST routes, changed the names to be unique, and then everything worked as expected.  I have tested that out on my end I get the same behavior - the GET route works as expected, but the POST route still gives me a value of undefined.

I should also point out that I have changed the routes around a bit to make them easier to maintain and so that we can more easily separate logic from one controller to the next.  For now this fixes the issue because in our workflow Page A now uses a POST route on submit to hit a controller validation function for Page A (checkInOut).  Then the validation function redirects to Page B (studySetup) using a GET route, which is where I need to know the current route so that I can do stuff in JS.

So while it's nice that this is (at least for now) no longer an issue for me, I would still question whether returning 'undefined' is the expected behavior for POST routes, or is this a bug?

**Comment by thoresuenert** [comment]
hi @kcchurch 

to be clear how the current function works:
It is looking for get routes only.

So when you want to check for a post route you need a second get route with the same url.

Otherwise you can fork the repo and change one specific line:
https://github.com/tightenco/ziggy/blob/253b919cddc196a5a9a94c5d1e406d1b57f700f1/src/js/route.js#L123
There you see the `indexOf('GET')` which is your "problem".

**Comment by kcchurch** [comment]
Hi @thoresuenert -

Perfect, thanks for your help!

**Comment by laxsmi** [comment]
I'm posting this here in case it helps others - a simple trick to use the package with POST routes is to call .url() on the route object.

`axios.post(route('post.store').url(), { ... })`

Thanks for the great package!
