### ISSUE TITLE
Add an artisan command to output the javascript to a file for inclusion

### ISSUE THREAD

**Issue by mattstauffer** [tightenco/ziggy#22]
In case someone wanted to add this to their build process, we could have a command:

```bash
php artisan ziggy:generate
```

which saves the output of the script into a file wrapped in an importable module.

We could even include a sample watcher so your build tool watches the routes files for changes and then re-runs the command when necessary.

**Comment by ctf0** [comment]
easier solution would have a config path of the js file, and the package watch that file and update it on the fly when app routes are changed, now the user only add the file to the build and forget about it.

**Comment by mattstauffer** [comment]
Great thinking @ctf0. The reason I didn't want to do that is because this requires the user to use Mix or whatever else, which limits them a bit. Rather, I'd love a solution that works in a variety of settings AND ALSO makes it super easy to use with mix/elixir.

Additionally, people can have custom routes files, so whatever we do would have to be helplessly configurable.. or just a guideline, which is my suggestion.

**Comment by ctf0** [comment]
i honestly wish if we dont use config files at all, but to keep things flexible we'll have to use the config like it or not, 

also you dont need to use any extra tool to use the js file, if you want you can simply call it with `{{ assets('js/ziggy.js') }}` just make sure the saved file path is under the public folder.

**Comment by mattstauffer** [comment]
Not using config would be great.

The extra tool would be for watching the routes files and triggering the regeneration of the JS file.

**Comment by ctf0** [comment]
extra tool, u mean `mix, elixir, etc.. ?` if yes then actually we can use something more clever and its within php, here is an exmaple https://github.com/ctf0/AssetCacheBust/blob/master/src/CacheBust.php

**Comment by mattstauffer** [comment]
Right.. but you have to run, and configure, that command. 

Think through *when* this would be running.

Something, somewhere, has to notice every time routes.php has changed, and trigger re-generation of the javascript file. What is that something?

**Comment by ctf0** [comment]
the only thing i can think about atm is an event that fires on each update to the routes list, then re-compile the js file.

or use a scheduler but not ideal.

**Comment by mattstauffer** [comment]
@ctf0 you can't do that. There's nothing in the framework itself that *watches* the routes files. *something* has to trigger a comparison. If you wanted you could write that watching so that every web request checked it, but that would miss a bunch of key workflows.

Scheduler is a bad idea because most people don't run cron locally.

This is a solved problem. "While I'm developing, watch certain files for changes and do something in response." What we need to do is A) make that possible and B) give examples/instructions for how to make it work on common watchers--namely mix and elixir.

**Comment by ctf0** [comment]
back to square one, but wait a minute !!!,

use `filemtime` to watch the route file and on each change, the `modified_at` time will change and thats what we use as a trigger to re-compile.

btw this is the same thing `{{ mix('someFile') }}` along with `mix.version()` use

or am i going in a loop ?

**Comment by mattstauffer** [comment]
@ctf0 Same issue. It's easy enough (although requires you to allow them to customize WHICH files are the routes files) to have PHP *check* a route file to see if it has changed since the last time it was checked.

But what's not built in to Laravel--other than in Elixir/Mix, which *already have tooling for this*--is watching files for modifications.

Don't stress. This is actually going to be relatively simple--you'll love it once you see it. We just need to write it. :)

**Comment by ctf0** [comment]
i will work on something today to test the `filemtime` theory , will send a PR once its done.

**Comment by quickliketurtle** [comment]
Hello, Taking a stab at this. 
I'm thinking the desired file would be something like this: 
```js
    var namedRoutes = JSON.parse('[]'),
        baseUrl = 'http://localhostmyapp.com/',
        baseProtocol = 'http',
        baseDomain = 'localhostmyapp.com',
        basePort = false;

    export {
        namedRoutes,
        baseUrl,
        baseProtocol,
        baseDomain,
        basePort
    }
```

This way you could do something like `import * from './ziggy.js';` then you get access to `ziggy.baseUrl` for example.  And optionally include route.js separately instead appending the contents to the end of this file. 

As a start to get this working I duplicated some logic from BladeRouteGenerator. I'm thinking of creating RouteGenerator that has all the 'shared logic, then having BladeRouteGenerator and FileRouteGenerator extend that. 

Thoughts?

**Comment by DanielCoulbourne** [comment]
I like this as a temporary solution. Ideally I want to play a little more with Babel today but I'm going to merge your PR in the meantime. Thanks for the contribution.

**Comment by quickliketurtle** [comment]
@DanielCoulbourne Cool. Glad it's useful, it was fun to work on. :-)
