### ISSUE TITLE
Documentation is missing the requirement of `vendor/tightenco/ziggy/src/js/route.js`

### ISSUE THREAD

**Issue by markokeeffe** [tightenco/ziggy#238]
### Expected Behavior
Documentation should explain that the `route.js` file needs to be imported from `vendor/tightenco/ziggy/src/js/route.js` when using the `ziggy:generate` artisan command.

### Current Behavior
Not documented.

I've put together an example for anyone that uses Laravel Mix and Vue (probably a lot of people who want to use Ziggy!)

**Comment by Albvadi** [comment]
Hi @markokeeffe, 
I've tried your example but it doesn't work... :disappointed_relieved: 

webpack.mix.js
```js
const mix = require('laravel-mix');
const path = require('path')

/*
 |--------------------------------------------------------------------------
 | Mix Asset Management
 |--------------------------------------------------------------------------
 |
 | Mix provides a clean, fluent API for defining some Webpack build steps
 | for your Laravel application. By default, we are compiling the Sass
 | file for the application as well as bundling up all the JS files.
 |
 */

mix.webpackConfig({
   resolve: {
       alias: {
           ziggy: path.resolve('vendor/tightenco/ziggy/src/js/route.js'),
       },
   },
})

mix.js('resources/js/app.js', 'public/js')
   .sass('resources/sass/app.scss', 'public/css');
```

app.js
```js
import route from 'ziggy'
import { Ziggy } from './ziggy'

/**
 * First we will load all of this project's JavaScript dependencies which
 * includes Vue and other libraries. It is a great starting point when
 * building robust, powerful web applications using Vue and Laravel.
 */

require('./bootstrap');

window.Vue = require('vue');

Vue.mixin({
    methods: {
        route: (name, params, absolute) => route(name, params, absolute, Ziggy),
    }
});

/**
 * The following block of code may be used to automatically register your
 * Vue components. It will recursively scan this directory for the Vue
 * components and automatically register them with their "basename".
 *
 * Eg. ./components/ExampleComponent.vue -> <example-component></example-component>
 */

// const files = require.context('./', true, /\.vue$/i)
// files.keys().map(key => Vue.component(key.split('/').pop().split('.')[0], files(key).default))

Vue.component('example-component', require('./components/ExampleComponent.vue').default);
Vue.component('user-import', require('./components/UserImport.vue').default);

/**
 * Next, we will create a fresh Vue application instance and attach it to
 * the page. Then, you may begin adding components to this application
 * or customize the JavaScript scaffolding to fit your unique needs.
 */

const app = new Vue({
    el: '#app',
});
```

Using in vue component
```vue
...
<script>
    export default {
        data() {
            return {
                query: "",
                users: [],
                routes: route('users.importUser')
            };
        },
....
```

Error console when compiling:
```bash
ERROR in ./resources/js/app.js
Module not found: Error: Can't resolve './ziggy' in 'C:\xampp\htdocs\proyect\resources\js'
 @ ./resources/js/app.js 2:0-32 15:44-49
 @ multi ./resources/js/app.js ./resources/sass/app.scss
```

Any idea??
Thanks!

**Comment by markokeeffe** [comment]
You will need to run the ‘ziggy:generate’ command to output your route declarations to ziggy.js


Mark

**Comment by Albvadi** [comment]
Before writing here, I had executed the command and the file ziggy.js had
been generated correctly in the path `resources/assets/js/ziggy.js`

But even so, it seems that when compiling he can't find it ...

**Comment by markokeeffe** [comment]
Depending on your Laravel version, you may need to change the path of the `ziggy:generate` command as it defaults to the 'legacy' `resources/assets/js/` directory. Laravel >=5.8 (I think) uses `resources/js/` instead.

I've just done a fresh Laravel install and these are the exact steps taken to get Ziggy to work with Vue:

**Set up in terminal:**
```bash
laravel new ziggy-laravel-test
cd ziggy-laravel-test
composer require laravel/ui --dev
composer require tightenco/ziggy
php artisan ui vue
yarn install
```

**webpack.mix.js**
```js
const mix = require('laravel-mix');
const path = require('path')

/*
 |--------------------------------------------------------------------------
 | Mix Asset Management
 |--------------------------------------------------------------------------
 |
 | Mix provides a clean, fluent API for defining some Webpack build steps
 | for your Laravel application. By default, we are compiling the Sass
 | file for the application as well as bundling up all the JS files.
 |
 */

mix.webpackConfig({
    resolve: {
        alias: {
            ziggy: path.resolve('vendor/tightenco/ziggy/src/js/route.js'),
        },
    },
})

mix.js('resources/js/app.js', 'public/js')
   .sass('resources/sass/app.scss', 'public/css');

```

**routes/web.php**
```php
<?php
Route::get('/', function () {
    return view('welcome');
})->name('welcome'); // Need at least one named route
```

**Run Ziggy**
```bash
php artisan ziggy:generate ./resources/js/ziggy.js
```

**resources/js/app.js**
```js
import route from 'ziggy'
import { Ziggy } from './ziggy'

/**
 * First we will load all of this project's JavaScript dependencies which
 * includes Vue and other libraries. It is a great starting point when
 * building robust, powerful web applications using Vue and Laravel.
 */

require('./bootstrap');

window.Vue = require('vue');

Vue.mixin({
    methods: {
        route: (name, params, absolute) => route(name, params, absolute, Ziggy),
    }
});

/**
 * The following block of code may be used to automatically register your
 * Vue components. It will recursively scan this directory for the Vue
 * components and automatically register them with their "basename".
 *
 * Eg. ./components/ExampleComponent.vue -> <example-component></example-component>
 */

// const files = require.context('./', true, /\.vue$/i)
// files.keys().map(key => Vue.component(key.split('/').pop().split('.')[0], files(key).default))

Vue.component('example-component', require('./components/ExampleComponent.vue').default);

/**
 * Next, we will create a fresh Vue application instance and attach it to
 * the page. Then, you may begin adding components to this application
 * or customize the JavaScript scaffolding to fit your unique needs.
 */

const app = new Vue({
    el: '#app',
});
```

** resources/js/components/ExampleComponent.vue **
```vue
<template>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Example Component</div>

                    <div class="card-body">
                        <a :href="route('welcome')" class="btn">Go Home</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</template>

<script>
    export default {
        mounted() {
            console.log('Component mounted.')
        }
    }
</script>
```

**Add built assets to your blade layout**
```html
<head>
    ...
   <script src="{{ mix('/js/app.js') }}" defer></script>
    <link href="{{ mix('/css/app.css') }}" rel="stylesheet">
</head>
```

**Add Vue component to your blade view**
```html
<div id="app" class="content">
    <example-component/>
</div>
```

**Build assets**
```bash
yarn run dev
```

**Comment by Albvadi** [comment]
> Depending on your Laravel version, you may need to change the path of the `ziggy:generate` command as it defaults to the 'legacy' `resources/assets/js/` directory. Laravel >=5.8 (I think) uses `resources/js/` instead.

I think this is the key because I´m using Laravel 6.
I have launched the Ziggy command by changing the output directory (`php artisan ziggy:generate ./resources/js/ziggy.js`) and reviewing all your steps and everything works perfectly.

Thank you so much for your help!!

**Comment by Albvadi** [comment]
Uhmm, One last thing...
I know its a Vue question, but I´m a newbie here... :slightly_frowning_face:

If I use `route()` in template, it´s working correctly, but If I use inside `data` or in a axios petition, the vue component crash with `[Vue warn]: Error in data(): "ReferenceError: route is not defined"`

```vue
<script>
    export default {
        data() {
            return {
                query: "",
                users: [],
                route: route('users.store')  // <-- here it´s crashing
            };
        },
        mounted() {
            console.log("Component mounted.");
        },
        methods: {
            importUser() {
                axios
                    .post(route('users.store'), {   // <-- here it´s crashing too
                        query: this.query
                    })
                    .then(res => {
                        this.userNotFound = false;
                        this.users = res.data;
                    })
                    .catch(err => {
                        this.userNotFound = true;
                        this.users = [];
                    })
                    .then(() => {

                    });
            }
        }
    };
</script>
```

**Comment by markokeeffe** [comment]
When using `Vue.mixin()`, you are essentially adding something to every component definition, so the following snippet: 
```js
Vue.mixin({
    methods: {
        route: (name, params, absolute) => route(name, params, absolute, Ziggy),
    }
});
```
adds a `route()` method to every component (accessible with `this.route('route.name.here')`.

For your example, you don't need to assign `route` at all in the `data() { ... }` portion of your component. You can fix your `importUser()` method by simply using `axios.post(this.route('users.store')`.

**To use `route()` outside Vue components:**

There are times where I need to use the route method outside of Vue components. For this, i use the following solution:

Make a separate `route.js` file that you can import wherever you need it:

**resources/js/route.js**
```js
import route from 'ziggy'
import { Ziggy } from './ziggy'

export default function (name, params, absolute) {
    return route(name, params, absolute, Ziggy)
}
```

Then you can import it into `app.js` to set up the global mixin:

```js
// resources/js/app.js
import route from '%/route'

Vue.mixin({
    methods: {
        route,
    },
})
```

Or in any other module / js file e.g. a VueX store:

```js
// resources/js/store/mymodule.js
import axios from 'axios'
import route from '../route'

// actions
const actions = {
    getExample({ state }) {
        return axios.get(route('my-route'))
    },
}
```

**Comment by Albvadi** [comment]
Using in axios works like a charm!
I´ll save this issue for the future, it´s a great explanation... 

Thanks so much for take your time to explain me basics of Js/Vue... :)

**Comment by DanielCoulbourne** [comment]
It looks like we're all good here! Love to see people helping each other

**Comment by aFluxx** [comment]
> When using `Vue.mixin()`, you are essentially adding something to every component definition, so the following snippet:
> 
> ```js
> Vue.mixin({
>     methods: {
>         route: (name, params, absolute) => route(name, params, absolute, Ziggy),
>     }
> });
> ```
> 
> adds a `route()` method to every component (accessible with `this.route('route.name.here')`.
> 
> For your example, you don't need to assign `route` at all in the `data() { ... }` portion of your component. You can fix your `importUser()` method by simply using `axios.post(this.route('users.store'))`.
> 
> **To use `route()` outside Vue components:**
> 
> There are times where I need to use the route method outside of Vue components. For this, i use the following solution:
> 
> Make a separate `route.js` file that you can import wherever you need it:
> 
> ```js
> // resources/js/route.js
> import route from 'ziggy'
> import { Ziggy } from './ziggy'
> 
> export default function (name, params, absolute) {
>     return route(name, params, absolute, Ziggy)
> }
> ```
> 
> Then you can import it into `app.js` to set up the global mixin:
> 
> ```js
> // resources/js/app.js
> import route from './route'
> 
> Vue.mixin({
>     methods: {
>         route,
>     },
> })
> ```
> 
> Or in any other module / js file e.g. a VueX store:
> 
> ```js
> // resources/js/store/mymodule.js
> import axios from 'axios'
> import route from '../route'
> 
> // actions
> const actions = {
>     getExample({ state }) {
>         return axios.get(route('my-route'))
>     },
> }
> ```

Hello,

When I try this approach I keep getting the following error:

``````
ERROR in ./resources/js/route.js
Module not found: Error: Can't resolve 'ziggy' in 'C:\Users\*****\Desktop\******\resources\js'
 @ ./resources/js/route.js 1:0-26 4:9-14
 @ ./resources/js/app.js
 @ multi ./resources/js/app.js ./resources/sass/app.scss
```

Normally I would think a node_module is missing, but I searched for the ziggy node module but it's an irc client: https://www.npmjs.com/package/ziggy

What am I doing wrong?

**Comment by markokeeffe** [comment]
ziggy.js comes in the composer package. The example adds a webpack alias:

mix.webpackConfig({ resolve: { alias: { ziggy: path.resolve('vendor/tightenco/ziggy/src/js/route.js'), }, }, })

Sorry about formatting, replying via email


Mark

**Comment by aFluxx** [comment]
Hey Marko,

With your implementation everything works fine.
There is a slight difference between your fix and the code which is shown in the documentation. 

The docs state:
`ziggy: path.resolve('vendor/tightenco/ziggy/dist/js/route.js'),` which does not seem to be exporting the route.

The fix that works:
`ziggy: path.resolve('vendor/tightenco/ziggy/src/js/route.js'),` which does export and does work.

The difference lies in the folder where it's fetched, **src** instead of **dist**

I am trying to test my Vue components, but until this moment I have not yet figured out how to import the **route()** helper in my jest tests _(but that is beyond the scope of this issue)_.

**Comment by markokeeffe** [comment]
@aFluxx I haven't had any issue using the file from `dist`. 

If you reference the `route.js` file from the `src` directory, you will most likely have to update your webpack config to ensure the `babel-loader` will include that file to transpile the JS into a browser friendly ES5 syntax. 

Requiring the `route.js` from the `dist` directory won't have this problem as it's already been transpiled.

**Comment by rognales** [comment]
This is my console. This error will only come when i use the route helper
````
Component mounted.
app.js:3436 [Vue warn]: Error in mounted hook: "TypeError: Cannot call a class as a function"

TypeError: Cannot call a class as a function
    at _classCallCheck (app.js:15290)
    at Route (app.js:15308)
    at VueComponent.route (app.js:14840)
    at VueComponent.mounted (app.js:2030)
    at invokeWithErrorHandling (app.js:4665)
    at callHook (app.js:7022)
    at Object.insert (app.js:5948)
    at invokeInsertHook (app.js:9143)
    at Vue.patch [as __patch__] (app.js:9360)
    at Vue._update (app.js:6748)
`````
My ExampleComponent.vue

````
 mounted() {
    console.log('Component mounted.')
    console.log(this.route('user.me'));
  },
```

Any idea on how to use the route() helper?

**Comment by bakerkretzmar** [comment]
@rognales if you're on Ziggy version `1.x` that path has changed: https://github.com/tighten/ziggy#advanced-setup

**Comment by t8ysn** [comment]
> @rognales if you're on Ziggy version `1.x` that path has changed: https://github.com/tighten/ziggy#advanced-setup

I am having the same problem as @rognales. 
Can you please give more insight into how to solve the issue @bakerkretzmar

**Comment by t8ysn** [comment]
> This is my console. This error will only come when i use the route helper
> 
> ```
> Component mounted.
> app.js:3436 [Vue warn]: Error in mounted hook: "TypeError: Cannot call a class as a function"
> 
> TypeError: Cannot call a class as a function
>     at _classCallCheck (app.js:15290)
>     at Route (app.js:15308)
>     at VueComponent.route (app.js:14840)
>     at VueComponent.mounted (app.js:2030)
>     at invokeWithErrorHandling (app.js:4665)
>     at callHook (app.js:7022)
>     at Object.insert (app.js:5948)
>     at invokeInsertHook (app.js:9143)
>     at Vue.patch [as __patch__] (app.js:9360)
>     at Vue._update (app.js:6748)
> ```
> 
> My ExampleComponent.vue
> 
> ```
>  mounted() {
>     console.log('Component mounted.')
>     console.log(this.route('user.me'));
>   },
> ```
> 
> Any idea on how to use the route() helper?
> ```

Did you manage to solve this?

**Comment by bakerkretzmar** [comment]
@t8ysn I believe this issue is related to aliasing `ziggy` with Laravel Mix. If you are on Ziggy v1, you should alias `vendor/tightenco/ziggy/dist` (Ziggy v0.x used `vendor/tightenco/ziggy/src/js/route.js`).

You can find more detailed setup instructions in the Readme: https://github.com/tighten/ziggy#advanced-setup.

If it's still not working for you please feel free to open a new issue!

**Comment by plweil** [comment]
@markokeeffe I have been trying, without success, to get Ziggy to work with Vuex, and am applying the pattern you gave earlier in this thread. I'm not sure whether anything significant has changed in Ziggy since then, but I can't seem to get "route" recognized. It keeps saying `ReferenceError: route is not defined`.

As for Mix aliases, the only one that allows Ziggy to work in Vue (v2) is

`'ziggy': path.resolve('vendor/tightenco/ziggy/dist/vue.es.js')`

Of course this is different from your alias, and maybe that's part of my problem. If you're able to offer any suggestions, I'd be grateful.

**Comment by markokeeffe** [comment]
I haven’t used this package for a couple of years so something may have
changed since my previous comments. I’m not sure without digging into it,
but I don’t have time at the moment I’m afraid, sorry about that.

**Comment by Jacobtims** [comment]
I get this error in my console:
![image](https://user-images.githubusercontent.com/75219092/144745190-5162ef7b-61d4-4272-b957-503c89b47a5a.png)

**Comment by plweil** [comment]
Is anyone using Ziggy successfully with Vuex and Vue 2? The examples from earlier in this thread no longer work. I've tried various ways of importing `route` into a Vuex store, but without success. They all return errors either during compilation or console errors on page load; e.g.;

`ReferenceError: route is not defined`

Using `this.route` in vuex axios actions does not work either — nor would I expect it to.

Obviously something significant has changed in the past year or two. Perhaps it's the Vue plugin... anyone?
