### ISSUE TITLE
Documentation is outdated

### ISSUE THREAD

**Issue by the94air** [tightenco/ziggy#241]
Continue #140 

I have noticed that the docs have been outdated for a quite long time and I need to make a move. I was willing to make the documentation auto-updated order by the project release using a CDN like so:

**Example**
https://cdn.jsdelivr.net/gh/tightenco/ziggy@0.8.0/README.md
https://cdn.jsdelivr.net/gh/tightenco/ziggy@0.7.0/README.md

then we compile the markdown on client-side using [showdown](https://github.com/showdownjs/showdown) package. It's so fast and easy plus you will just need to update the readme only on every release. Vuepress or Jigsaw is another choice of course but it requires a bit of more work.

But first, we need to decide if we can relay on sperate documentation or get rid of it and just use the GitHub readme. We can add Google Tag Manager to the documentation and wait for a week or so to get a reliable result of the number of visitors. Though If you think we need to remove it right away we can do that as well :smile:.

**Comment by DanielCoulbourne** [comment]
Lets either generate it or drop it.
Manual maintenance is going to be impossible long term.

**Comment by bakerkretzmar** [comment]
We're going to just use the Readme as documentation.
