### ISSUE TITLE
Ziggy Script in Comment

### ISSUE THREAD

**Issue by paulotra** [tightenco/ziggy#254]
### Expected Behavior
Load ziggy script first.

### Current Behavior
I have some issues with the ziggy script in the server, works fine on local. the script commented and fires and error `current` is undefined. Is there an option to load the routes first before my app.js? 

### Currently installed Laravel version:
`5.8.35`

### Currently installed Ziggy version
`0.8.0`

<img width="1060" alt="Screen Shot 2019-11-02 at 5 18 21 PM" src="https://user-images.githubusercontent.com/20724804/68068974-a0214480-fd95-11e9-9e20-09bca590ceda.png">

**Comment by bkintanar** [comment]
Hahaha!
