### ISSUE TITLE
Only return user relevant routes

### ISSUE THREAD

**Issue by SuperDJ** [tightenco/ziggy#258]
### Expected Behavior

Only show the routes that apply to the middleware. For example a guest user should only be able to see the routes that apply to a guest user. This will not only improve peformance as not all routes are always returned. It will also improve security as a guest user will not know about available auth routes.

### Current Behavior
Modification

### Currently installed Laravel version:
`6.5.2`

### Currently installed Ziggy version
`0.8.1"`

**Comment by bakerkretzmar** [comment]
Pretty sure [Advanced Whitelisting Using Groups](https://github.com/tightenco/ziggy#advanced-whitelisting-using-groups) covers this.
