### ISSUE TITLE
How do I use this package with jest?

### ISSUE THREAD

**Issue by aFluxx** [tightenco/ziggy#264]
### Currently installed Laravel version:
`6.6.*`

### Currently installed Ziggy version
`0.8.1`

Hello, I'm in the course of testing my vue components, but I'm stuck on Vue components that use this package. For some reason I am not able to import the route helper. In the hopes of figuring this out I'm launching a long shot here, maybe someone has had a similar issue.

These are my imports atop of my `.spec.js` file
```js
import route from '../../../vendor/tightenco/ziggy/src/js/route.js';
import { Ziggy } from '../../../resources/js/ziggy.js';
```

And an example piece of code from the components  `<script>` tags
```js
   mounted() {
        axios.get(route('clock_group.user.followings')).then(res => {
            this.followings = res.data;
        });
        axios.get(route('clock_group.members', this.clockGroupId)).then(res => {
            this.members = res.data;
        });
    },
```

But I keep getting the following error `ReferenceError: route is not defined`.

EDIT:
If this is out of scope, feel free to close the issue without a solution.

**Comment by Kovalchuk91** [comment]
@aFluxx one option is to map it in your package.json file:
`
{
 "jest": {
     "moduleNameMapper": {
         "^ziggy$": "<rootDir>/vendor/tightenco/ziggy/dist/js/route.js"
     }
 }
}
`

Another option it to mock this file in jest (https://jestjs.io/docs/ru/manual-mocks). Just create a ziggy.js in __mocks__ folder and export a function that will mock ziggy's one.

**Comment by aFluxx** [comment]
Thanks Koval, gonna try it out!

**Comment by jakebathman** [comment]
Gonna close this issue, but if anyone has more info feel free to reply again.
