### ISSUE TITLE
ReferenceError: route is not defined

### ISSUE THREAD

**Issue by AN1BRA** [tightenco/ziggy#265]
I have an issue with Ziggy, I was using it first with the directive `@routes` but after switching to the artisan method the `route` helper function fails to import,
###Steps to reproduce
in webpack.mix:
```
ziggy: path.resolve(
      __dirname,
      'vendor/tightenco/ziggy/dist/js/route.js'),
ziggyRoutes: path.resolve(
       __dirname,
      'resources/assets/js/ziggy.js'),
```
in app.js:
```
import route from 'ziggy';
import { Ziggy } from 'ziggyRoutes'

Vue.mixin({
    methods: {
        route: (name, params, absolute) => window._route(name, params, absolute, Ziggy),
    }
});
```

### Current Behavior

> [Vue warn]: Error in data(): "ReferenceError: route is not defined"

### Currently installed Laravel version:
`5.7`

### Currently installed Ziggy version
`v0.6.8.1`

**Comment by jakebathman** [comment]
Are you using Vue with your project? If so, can I see what the whole `app.js` file looks like?

If not, you only need to add those first two lines to your `app.js` file:

```js
import route from 'ziggy';
import { Ziggy } from 'ziggyRoutes'
```

**Comment by Acen** [comment]
When are you connecting `window._route`?

The Vue mixin makes it so that `this.route` connects to this function you're defining here. But afaik by default Ziggy doesn't push anything into the global space by default.

**Comment by RichardDern** [comment]
I have the exact same problem. I carefully followed the Artisan section of the readme, after ```composer require tightenco/ziggy```.

In _webpack.mix.js_, I added:

```
// [...]
const path = require('path');

mix.webpackConfig({
    resolve: {
        alias: {
            ziggy: path.resolve('vendor/tightenco/ziggy/dist/js/route.js'),
        },
    },
});
// [...]
```

In _app.js_: 

```
// [...]
require('./bootstrap');

import route from 'ziggy';
import { Ziggy } from './ziggy';

window.Vue = require('vue');

Vue.mixin({
    methods: {
        route: (name, params, absolute) => route(name, params, absolute, Ziggy),
    }
});
// [...]
```

Then I generated the _ziggy.js_ file:

```php artisan ziggy:generate "resources/js/ziggy.js"```

So the _ziggy.js_ file is in the same directory as _app.js_ (you should probably update default location to match new Laravel's structure BTW)

Then:

```npm run dev```

Compiles without any problem.

Everything works if I add ```@routes``` to my blade view, but if I don't, I get "ReferenceError: Can't find variable: route".

**Comment by Mirkin-source** [comment]
Same problem here!

In **webpack.mix.js**, I added:
```
const path = require('path')
mix.webpackConfig({
    resolve: {
        alias: {
                ziggy: path.resolve('vendor/tightenco/ziggy/dist/js/route.js'),
        },
    },
});
```

In **app.js** (not using Vue):
```
import route from 'ziggy';
import { Ziggy } from '../assets/js/ziggy'
```

In **app.js** it creates:
```
// [...]
var Ziggy = {
  namedRoutes: {
    "debugbar.openhandler": {
      "uri": "_debugbar\/open",
      "methods": ["GET", "HEAD"],
      "domain": null
    },
    "debugbar.clockwork": {
      "uri": "_debugbar\/clockwork\/{id}",
      "methods": ["GET", "HEAD"],
      "domain": null
    },
    "debugbar.telescope": {
      "uri": "_debugbar\/telescope\/{id}",
      "methods": ["GET", "HEAD"],
      "domain": null
    },
    "debugbar.assets.css": {
      "uri": "_debugbar\/assets\/stylesheets",
      "methods": ["GET", "HEAD"],
      "domain": null
    },
// [...]
```
Everything works if I @routes is added in the blade view, but if it isn't, I get "ReferenceError: Can't find variable: route".

**Comment by mazedlx** [comment]
Here's what my setup looks like, it works without the `@routes` blade directive:

In `app.js`:
```js
[...]
import route from 'ziggy';
import { Ziggy } from './ziggy';

window.route = route;
window.Ziggy = Ziggy;
Vue.mixin({
  methods: {
    route: (name, params, absolute) => route(name, params, absolute, Ziggy),
  }
});
```

in `webpack.mix.js`:
```js
mix.webpackConfig({
  resolve: {
    alias: {
      ...
      ziggy: path.resolve('vendor/tightenco/ziggy/dist/js/route.js'),
    },
  },
});
```

Compiles without errors, and everything works as expected. Hope this helps.

**Comment by RichardDern** [comment]
I confirm @mazedlx setup. Two points changed between my setup and his.

These two lines are required:

```
window.route = route;
window.Ziggy = Ziggy;
```

And in ```webpack.mix.js```, I used the minified ```route.js```, whereas @mazedlx referred to the non-minified ```route.js```.

It works as expected now. thank you very much !

**Comment by bakerkretzmar** [comment]
As pointed out above, this is just a question of bundlers not propagating `route` and `Ziggy` into the global scope.

If you're using the `route()` helper in your app Javascript files, you need to `import route from 'ziggy'` and `import { Ziggy } from './ziggy'` wherever you want to use them.

If you will later need to call `route()` somewhere else, like from other scripts loaded later on the page and not bundled, add `route` and `Ziggy` to the global scope as demonstrated above with `window.route = route;` and `window.Ziggy = Ziggy;`. Using the `@routes` Blade directive accomplished this too.

If you're using Vue, as the original issue describes, you don't need `route` and `Ziggy` on the window and you can do what they were describing:

```js
// webpack.mix.js

// ...

mix.webpackConfig({
    resolve: {
        alias: {
            ziggy: path.resolve('vendor/tightenco/ziggy/src/js/route.js'),
            ziggyRoutes: path.resolve('resources/js/ziggy.js'),
        },
    },
});
```

```js
// app.js:

import route from 'ziggy';
import { Ziggy } from 'ziggyRoutes';

// ...

Vue.mixin({
    methods: {
        route: (name, params, absolute) => route(name, params, absolute, Ziggy),
    },
});
```
