### ISSUE TITLE
Suggestion: Extract JS code into npm package.

### ISSUE THREAD

**Issue by Zlob** [tightenco/ziggy#273]
First of all, your library is awesome, thank you very much.

But in some cases it's not convenient to have JS code in PHP library. For example, in our project we build frontend separately from backend. That means that we have to install all PHP requirements only because of one js file, which leads to some specific problems with Docker image and e.t.c. I understand, that, as you [mentioned before](https://github.com/tightenco/ziggy/issues/24#issuecomment-322340240), maintain two packages in two different package repositories is much more harder than one. But I would appreciate it if you could consider possibility to extract JS part into NPM package.

**Comment by DanielCoulbourne** [comment]
Feel free to do it yourself, but I have no intention of maintaining a NPM repo.
