### ISSUE TITLE
Please publish to npm 

### ISSUE THREAD

**Issue by benallfree** [tightenco/ziggy#277]
This ticket is a placeholder to follow up on #276 

Currently, this package is not published on npm.

This would be helpful for those of us creating stand-alone SPA apps that interface with a Laravel-based API, but do not have any need for `composer` dependencies.

For example, I am using next.js to create a SPA that calls my Laravel API. Completely separate project. I use `php artisan ziggy:generate ../path/to/spa/src/ziggyData.js` to generate the Ziggy bindings and include them in my SPA, but I also need to reference the `route.js` from this package. Unfortunately, it is not currently published on npm.

**Comment by DanielCoulbourne** [comment]
I think I'm fine with this but we would need some sort of workflow to make sure that Composer and NPM version numbers stay in sync. Probably something in CI

**Comment by benallfree** [comment]
@DanielCoulbourne Is that something I can do as part of #276? Maybe I could add a prepublish check to make sure the `composer.json` and `package.json` versions match?

**Comment by bakerkretzmar** [comment]
Closed by #286.
