### ISSUE TITLE
Readme gif/example is wrong?

### ISSUE THREAD

**Issue by JesseLeite** [tightenco/ziggy#28]
Is it something I am doing, or is gif and code example wrong with `{id: 123}` the ID as key?

![](http://b3.ms/KkdA3J5v93Jq)

**Comment by mattstauffer** [comment]
@JesseLeite what's your map? It matches the variable name; so I'm guessing you're doing this:

```php
Route::get('/posts/{post}', function () {})->name('posts.show');
```

I think Laravel may actually ignore that variable name and instead expect just an array. We could potentially just add a second syntax where you pass an un-keyed array of values?

**Comment by mattstauffer** [comment]
(that is: the readme assumes this instead:

```php
Route::get('/posts/{id}', function () {})->name('posts.show');
```

**Comment by JesseLeite** [comment]
@mattstauffer Neither

```php
Route::resource('posts', 'PostController');
```

Standard Laravel resource route/controller, which automatically creates resource names like:

![](http://b3.ms/lrXMDX1kMb1j)

With your approach, how would you handle nested resource routes like this?

```php
Route::get('/events/{event}/venues/{venue}', function () {})->name('events.venues.show');
```

Since you can't use `{id}` twice for two different model resources?

Btw, I realize your package works perfectly.  I'm just saying the docs aren't clear if you are a `Route::resource()` user 🙂

**Comment by JesseLeite** [comment]
>We could potentially just add a second syntax where you pass an un-keyed array of values?

Btw, I love the unkeyed array approach as well, since Laravel's route works that way in PHP ...if anything, for consistency with Laravel 👌

**Comment by mattstauffer** [comment]
@JesseLeite AH! Yah, I think it should be *clearer*--but I also think that the whole using keys thing is problematic in the first place, because Laravel's route helper *doesn't use keys* if I remember correctly.

I'll write it up a bit more shortly.

**Comment by JesseLeite** [comment]
>but I also think that the whole using keys thing is problematic in the first place, because Laravel's route helper doesn't use keys if I remember correctly.

Yeah, I think you are on right track with allowing non-keyed array, though it could be added functionality in case people want to be super explicit with keys for whatever reason?

In Laravel, I've always passed in raw IDs (without keys):

```php
route('events.venues.show', [$event->id, $venue->id])
```

Or passed in models, as Laravel is smart enough to resolve the IDs:

```php
route('events.venues.show', [$event, $venue])
```

**Comment by JesseLeite** [comment]
I just PR'd in a possible implementation for the unkeyed array idea.  See #30.

**Comment by DanielCoulbourne** [comment]
Thanks so much for your PR @JesseLeite.

I really like the "whole object" approach and @calebporzio and I just discussed it on our podcast. I just can't see the way to make it work right now.

I would be thrilled to be wrong though

**Comment by JesseLeite** [comment]
@DanielCoulbourne the whole object approach could work, but I agree it would be more complex.

I think Illuminate Models have a `getkey() // returns 'id'` method or something similar.  It would be cool to piggy back off of that somehow.  The weird part is that each model could technically have a different primary key field name, so getting a list of those for each model would be awkward.  I'm not even sure there is a clean way to get a list of all the models in an app to loop over them?

**Comment by DanielCoulbourne** [comment]
I think this can be closed now?

**Comment by JesseLeite** [comment]
>"when" you come up with a brilliant solution to the "whole object" thing, I'm into it.

Haha!  Not so brilliant, but it's something 😬: https://github.com/tightenco/ziggy/pull/37
