### ISSUE TITLE
How to setup package need more info 

### ISSUE THREAD

**Issue by KalimeroMK** [tightenco/ziggy#281]
Hi I have problem with setup tightenco/ziggy on laravel 5.8

Add Ziggy composer require tightenco/ziggy
run php artisan ziggy:generate and move it to same folder with app.js 
Include our Blade Directive (@routes) somewhere in your template before your main application

add 
```
//ziggy implementation
import 'global-helpers';
import Vue from 'vue';
import {Ziggy} from './ziggy';
import route from '/vendor/tightenco/ziggy/dist/js/route';
window.Ziggy = Ziggy; // this was missing from your setup

Vue.mixin({
    methods: {
        route: (name, params, absolute) => route(name, params, absolute, Ziggy),

    }
});
// end ziggy implementation
```
in app.js 
1st is working one manual second trows error 
```
methods: {
            generate() {
                axios.post(`/api/user/${this.user.eid}/2fa`)
                    .then(res => {
                        this.google2fa_secret = res.data.secret;
                        this.qr_code = res.data.qr;
                    })
                    .catch(this.handleError);
            },
```
first trows sintax error

```
  disable() {
                 axios.post(route('api.user.2fa', ${this.user.eid}))`, {disable: true})
                    .then(res => {
                        this.google2fa_secret = res.data.secret;
                        this.qr_code = '';
                        this.toggle = false;
                    })
                    .catch(this.handleError);
            }
        },
```
returns
 Syntax Error: SyntaxError: /Users/zoran/PhpstormProjects/mxco-vagrant/tether/resources/js/vue/components/TwoFactorAuth.vue: Unexpected token, expected "," (94:46)

  92 |     methods: {
  93 |         generate() {
> 94 |             axios.post(route('api.user.2fa', ${this.user.eid}))
     |                                               ^
  95 |                 .then(res => {
  96 |                     this.google2fa_secret = res.data.secret;
  97 |                     this.qr_code = res.data.qr;

**Comment by dfrey382** [comment]
add how to install to vue ;yarn add ziggy npm install ziggy
