### ISSUE TITLE
Routes js file path is relative to current dir rather than project root

### ISSUE THREAD

**Issue by modstore** [tightenco/ziggy#282]
### Expected Behavior
Routes js file should be generated in the path relative to the project root.

### Current Behavior
File is generated relative to the current directory when the command is run.
Eg. my CI deploy command:
/usr/bin/php ~/releases/1/artisan ziggy:generate "./resources/js/generated/ziggy.js" -vvv
The file was generated at ~/resources/js/generated/ziggy.js rather than ~/releases/1/resources/js/generated/ziggy.js

### Currently installed Laravel version:
`7.5.2`

### Currently installed Ziggy version
`0.9.0`

### More info
I couldn't figure out for a while why the file wasn't being generated (but it actually was, just not where I expected it to be). I was running the command with -vvv but there's no debug output, it would be useful to show the final path that the file is generated to in this case. That would have made things much easier to figure out.

Thanks for a great package though!

**Comment by bakerkretzmar** [comment]
Thanks! Will be fixed shortly.
