### ISSUE TITLE
blacklist is being ignored when routes are cached

### ISSUE THREAD

**Issue by ankurk91** [tightenco/ziggy#288]
### Expected Behaviour
It should respect the `blacklist` defined in `config/ziggy.php`

```php
<?php
return [

    'blacklist' => [
        'debugbar.*', 'horizon.*', 'passport.*', 'telescope.*', 'ignition.*',
        'api.*', 'webhooks.*',
    ],

];
```
### Current Behaviour
When routes are cached with `php artisan route:cache`, it ignores the config and dump all routes on blade template.

### Currently installed Laravel version:
`7.7.1`

### Currently installed Ziggy version
`v0.9.0`

### Example route from your Laravel Routes file.
_i.e. -_
```php
// NA
```
### Contents of Ziggy.namedRoutes
_In dev tools type `Ziggy.namedRoutes` and copy the result here._

### Ziggy call in context
_i.e. –_
```javascript
// NA
```

**Comment by bakerkretzmar** [comment]
I can't reproduce this locally—I have a bunch of named routes and I'm blacklisting them with wildcards and with specific names, cached and uncached, and it's working as expected. It even correctly picks up my changes to `config/ziggy.php` while routes are cached.

Can you post the complete contents of both your `config/ziggy.php` and the output of `Ziggy.namedRoutes` with and without routes cached?

**Comment by ankurk91** [comment]
I am not doing anything special in my routes, i have 3 different Laravel apps with same issue.

All of them have al-least 2 sub-domains, for example.
```
admin.example.com
api.example.com
```

I am trying to make a minimal codebase to re-produce this issue, but could not.
I will re-open this issue, if i found something,
