### ISSUE TITLE
Missing documentation for using Ziggy from an npm package CDN

### ISSUE THREAD

**Issue by bakerkretzmar** [tightenco/ziggy#292]
Now that Ziggy is published on npm, it should be possible to use it with something like `cdnjs` or `unkpkg`. You'd need to import the generated routes yourself, but as long as you declare those first you should be able to do something like this:

```html
<!-- import/define the Ziggy object up here -->

<script defer src="https://unpkg.com/ziggy-js@0.9.3/dist/js/route.min.js"></script>

<script type="text/javascript">
    route('home'); // this should work
</script>
```

**Comment by ankurk91** [comment]
@bakerkretzmar 
Yes, it should work.
```js
route('home');
```
