### ISSUE TITLE
Issue on getting parameters if project is under a subfolder

### ISSUE THREAD

**Issue by Yeenot** [tightenco/ziggy#295]
Logic:
Everytime the country/language selector is changed, I need to redirect the user to the same page along with the other parameters that is in the route/url. In this case, I am on a page and trying to get the parameters.

Route:
```
Route::group(['prefix' => '{country?}/{language?}', 'middleware' => 'locale'], function() {
    Route::get('products/{id}', 'ProductController@show')->name('public.products.show');
});
```

JS:
`route().params`

Example: 
https://domain.com/subfolder/{country}/{language}/products/{id}
https://domain.com/subfolder/ph/en/products/4

### Expected behavior
`{
    country: 'ph',
    language: 'en',
    id: '4'
}`

### Current behavior

`{
    country: 'subfolder',
    language: 'ph',
    id: 'products'
}`

### Ziggy
 baseUrl: 'https://domain.com/subfolder/',
 baseProtocol: 'https',
 baseDomain: 'domain.com',

### Versions

- **Laravel**: 7.0
- **Ziggy**: 0.9.0

**Comment by bakerkretzmar** [comment]
@Yeenot are you generating the URL from those parameters, or are you on a page and trying to get the parameters with `route().current()`? Can you share the Laravel route definition too please?

**Comment by Yeenot** [comment]
@bakerkretzmar sorry about the lack of information, I have edited now the description above and added some description logic to what I was trying to do.

Yesterday, I came up with a temporary solution where I have passed the uri and template to the `extractParams` method but without the base url.

```
const route = require('ziggy');
const { Ziggy } = require('^resources/ziggy');

module.exports = (name, params, absolute) => {
    const router = route(name, params, absolute, Ziggy);

    // custom method for getting parameters
    router.getParameters = function(name) {
        var url = window.location.href.replace(Ziggy.baseUrl, '');
        var template = Ziggy.namedRoutes[name].uri;
        return router.extractParams(url, template, '/');
    };
    return router;
}
```

**Comment by bakerkretzmar** [comment]
Ok I think I understand, thanks. Is your whole Laravel app in a subfolder? Is your `APP_URL` environment variable set to `https://domain.com/subfolder/` (including the subfolder)?

Will look into this.

**Comment by Yeenot** [comment]
@bakerkretzmar yes, the whole laravel app is inside a subfolder and the `APP_URL` is being set to that but without the end slash `/` like `https://domain.com/subfolder`

**Comment by bakerkretzmar** [comment]
@Yeenot can you provide the output of `Ziggy.namedRoutes` for your `products/` route above?

I have a feeling this issue is caused by how Laravel generates the route definitions, and since Laravel doesn't support being installed in a subdirectory there may not be much we can do.

**Comment by Yeenot** [comment]
@bakerkretzmar Sure, here it is. But I really think that Laravel supports it, we just need to set a`APP_URL` and add a public path on webpack for the assets.

Named Routes:
```
"public.products.show": {
      "uri": "{country?}\/{locale?}\/products\/{id}",
      "methods": ["GET", "HEAD"],
      "domain": null
    },
```

Webpack:
```
mix.webpackConfig({
       output: {
        publicPath: `/subfolder/`
    }
});
```

**Comment by Yeenot** [comment]
@bakerkretzmar My guess is that the reason for this is you're using `window.location.pathname.slice(1)` on extracting params where it would include the `subfolder` path?

```
get params() {
        const namedRoute = this.ziggy.namedRoutes[this.current()];

        return Object.assign(
            this.extractParams(
                window.location.hostname,
                namedRoute.domain || '',
                '.'
            ),
            this.extractParams(
                window.location.pathname.slice(1),
                namedRoute.uri,
                '/'
            )
        );
    }
```
