### ISSUE TITLE
The given data was invalid (laravel ecommerce) validation error (remote server)

### ISSUE THREAD

**Issue by connectinghub007** [tightenco/ziggy#297]
Im using laravel ecommerce system, the problem is when I upload a new image from gallery (remote server), it gives me 422 error but works fine on my localhost. The error shows

`'File media   'Status 422  'type xhr      initiator media.js?v=1.1.5:1

It's shows something like validation error. When I go to online json validator, its shows me after paste media.js code, it shows`

`Parse error on line 1: !function(e){var t={ ^ Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[', got 'undefined'

media.js link attached. thanks

[https://www.cheaper.pk/modules/media/admin/js/media.js](url)

**Comment by bakerkretzmar** [comment]
Could you fill out the issue template please, so we understand your setup and what the expected behaviour is? I'm not certain that this is an issue with Ziggy at all.

From a quick look at that file, on line 275 `route: "admin.file_manager.index",` may need to be `route: route("admin.file_manager.index"),`.

I don't think using a JSON validator is going to help you here, that file isn't JSON.

**Comment by connectinghub007** [comment]
> Could you fill out the issue template please, so we understand your setup and what the expected behaviour is? I'm not certain that this is an issue with Ziggy at all.
> 
> From a quick look at that file, on line 275 `route: "admin.file_manager.index",` may need to be `route: route("admin.file_manager.index"),`.
> 
> I don't think using a JSON validator is going to help you here, that file isn't JSON.

It's fleetcart. you may login if you wish to check

**Comment by bakerkretzmar** [comment]
If you're having an issue with FleetCart, I would suggest contacting them.

I don't see any indication that this is an issue with Ziggy, could you please provide a full log / stack trace of the error you're seeing, as well as your Laravel and Ziggy version numbers, your route definitions, the output of `Ziggy.namedRoutes`, and an example of the Ziggy calls you're making? Thanks.

**Comment by bakerkretzmar** [comment]
I'm going to close this for now as it doesn't appear to be an issue with Ziggy and we don't have enough information to look into it further. Feel free to comment below or open another issue if you're still having trouble. Thanks!
