### ISSUE TITLE
Can Ziggy be used with a framework like Nuxt.js?

### ISSUE THREAD

**Issue by connecteev** [tightenco/ziggy#298]
This is more of a question rather than a bug report or feature request, please redirect me if this is not the right place to ask this question.
I just discovered Ziggy and it looks like it would be useful to have named routes be accessible in Javascript.

My tech stack is Laravel (APIs) and Nuxt.js (for the front-end). Is it possible to have the Laravel routes be available in Nuxt.js? Or is this only for Laravel-only code?

**Comment by bakerkretzmar** [comment]
Yes, you can use Ziggy client-side however you like, including with Nuxt. I don't know much about Nuxt, but all you need to do is import the `route` function and the generated routes file. You can generate your routes file [using the `ziggy:generate` Artisan command](https://github.com/tightenco/ziggy#artisan-command).

My guess is this isn't too different from [using Ziggy with Vue](https://github.com/tightenco/ziggy#using-with-vue-components).

Take a look at the Readme in this repo for more usage examples.

**Comment by bakerkretzmar** [comment]
See also #260.

**Comment by connecteev** [comment]
@bakerkretzmar thanks for the thoughts, I'm a bit confused by this.
Nuxt is a vue framework that has all my front-end code, it's a completely different codebase from my laravel codebase (backend). How would the ziggy:generate Artisan command apply here? Won't I have to manually copy the file from my laravel codebase to Nuxt? Does it make sense to use?
Thanks..

**Comment by bakerkretzmar** [comment]
@connecteev if they're in separate codebases, yes, you would have to run `php artisan ziggy:generate` in your Laravel app and then either copy the generated file over, or make it publicly available on your server and load it dynamically into your Nuxt app over the network.

#272 started work on adding this functionality so it's built-in, but it should be straightforward (if a bit tedious) to do manually.

As for whether that makes sense, you'll have to decide, but I think so. You can now install Ziggy as an NPM package (`ziggy-js`) which will provide the `route()` function, and if you make `php artisan ziggy:generate` part of your Laravel app's deployment process then the only tricky part is getting the routes file, either by copying or requesting it. Personally I think that setup cost is well worth it!

**Comment by connecteev** [comment]
@bakerkretzmar thanks for clarifying, this is very helpful. Bookmarked and we will be looking into using Ziggy in our codebase. Thanks..
