### ISSUE TITLE
Eslint triggers

### ISSUE THREAD

**Issue by robov** [tightenco/ziggy#318]
eslint triggers the following notifications:

392:3   error  for..in loops iterate over the entire prototype chain, which is virtually never what you want. Use Object.{keys,values,entries}, and iterate over the resulting array  no-restricted-syntax
  392:3   error  The body of a for-in should be wrapped in an if statement to filter unwanted properties from the prototype                                                             guard-for-in
  397:10  error  Prefer default export                                                                                                                                                  import/prefer-default-export

**Comment by bakerkretzmar** [comment]
I'm not sure we actually have any `for ... in` loops in the source, are you sure this is coming from Ziggy?

**Comment by robov** [comment]
Yes, because when I ignore that file, everything lints fine
btw.. awesome package !

**Comment by bakerkretzmar** [comment]
Thanks, glad you're finding it useful!

If I'm understanding correctly these warnings are generated by your eslint config, right? There's no runtime error or actual issue with Ziggy itself? If that's the case, just configure eslint to ignore the file as you mentioned.
