### ISSUE TITLE
Make it possible to hide some routes

### ISSUE THREAD

**Issue by m1guelpf** [tightenco/ziggy#36]
Example: I want to use this in my application, but I don't want to show the /admin/* routes exist

**Comment by DanielCoulbourne** [comment]
Hey @m1guelpf!

This is my most requested feature and I'm actively working on it. Should ship today or tomorrow.
You can check out the active discussions over at #16

I'm closing this issue as a dupe for now, but if you go follow that issue you should get notified when I push the new release. I'll probably tweet about it too so you may see it there.

Thanks for the support of the package AND the podcast 😄
