### ISSUE TITLE
Test in Laravel 5.5

### ISSUE THREAD

**Issue by DanielCoulbourne** [tightenco/ziggy#42]
I think we should be okay, but I saw some changes to `getRoutesByName()` so I may need to change some things for Laravel 5.5.

Anyone have a good versioning strategy to have a LTS version that works with 5.4?

**Comment by JesseLeite** [comment]
What about detecting laravel/framework version at runtime via something like `app()->version()`, and handling both implementations in the same master branch?  This way Ziggy users won't have to think about syncing a Ziggy version with laravel/framework?

**Comment by stevebauman** [comment]
Works fine for me in Laravel 5.5 :)

**Comment by DanielCoulbourne** [comment]
Sweet! I'll run a few more tests myself then close this.
