### ISSUE TITLE
Laravel Modules Design?

### ISSUE THREAD

**Issue by Robert-Hansen** [tightenco/ziggy#44]
Hi
I just started to use a Laravel Modules because I like it better than the normal folder structure so my question is does this work with https://github.com/nWidart/laravel-modules ?
I haven't tried it myself just yet been busy doing some other stuff so if someone knows if it works please let me know other than that keep up the good work! ;)

Regards

**Comment by Robert-Hansen** [comment]
I just tried it and it works so if anyone else uses the laravel-modules package it works ;)

**Comment by DanielCoulbourne** [comment]
Nice! Thanks!
