### ISSUE TITLE
Macro implementation

### ISSUE THREAD

**Issue by dbonner1987** [tightenco/ziggy#45]
Following up from my post on twitter yesterday (https://twitter.com/dbonner1987/status/889252632023490564) and my adventures down the rabbit hole with the routing system in Laravel. 

I'm now using just a single `Route::macro` implementation that will add filtering to routes. Security through obscurity is not smart but I got a bee in my bonnet and became a bit engrossed in getting a macro working cleanly.

What I have settled on for the time being is:

```php
// Usage
Route::blacklist()->name('tags.index')->get('/tags', 'TagsController@index');

// Implementation
Route::macro('blacklist', function () {
    return new class($this) {
        protected $router;
        
        public function __construct($router)
        {
            $this->router = $router;
        }

        public function __call($method, $parameters)
        {
            call_user_func_array([$this->router, $method], $parameters);

            if ($method === 'name') {
                config()->set('ziggy.blacklist', array_merge(
                    config('ziggy.blacklist', []), [array_get($parameters, 0, null)]
                ));
            }

            return $this;
        }
    };
});
```
Currently this allows all methods chained on to `blacklist` to be in any order.

Looking for some thoughts on this implementation.

**Comment by DanielCoulbourne** [comment]
Hey! Thanks for the issue. I'll be knocking out a ton of maintenance stuff tomorrow so I'll have more in-depth thoughts then.

Does this work with groups?

**Comment by dbonner1987** [comment]
Unfortunately groups are a different story. Because the group doesn't receive any information from the closure, we can't get the names from the actual routes. I'm forcing myself to not extend the Router, so I'm thinking about swapping the Router instance in and out with an anonymous class that extends the router when blacklisting is required. Haven't had a chance to implement it yet.

Another option that works in principal is using the route actions/attributes array works but it would require an alteration to `Tightenco\Ziggy\RoutePayload` to check for the "blacklist" key.

```php
Route::macro('blacklist', function () {
    return new class($this) {
        protected $router;

        public function __construct($router)
        {
            $this->router = $router;
        }

        public function __call($method, $parameters)
        {
            if ($method === 'group') {
                $parameters[0]['blacklist'] = true;
            }

            $route = call_user_func_array([$this->router, $method], $parameters);

            if ($route instanceof Router) {
                $route->setAction(array_merge($route->getAction(), ['blacklist' => true]));
            }

            return $route;
        }
    };
});
```

**Comment by DanielCoulbourne** [comment]
@dbonner1987 If you want to PR this I think I'm okay with it.

**Comment by dbonner1987** [comment]
@DanielCoulbourne Excellent, hoping to get a look at implementing it over the weekend.

**Comment by DanielCoulbourne** [comment]
Awesome! It looks like a great, viable, idea.

**Comment by dbonner1987** [comment]
@DanielCoulbourne an initial implementation of the Macro: https://github.com/dbonner1987/ziggy/commit/283396aafa30e90386fe056d8c62e9a059c6b9dc

I'm not entirely happy with it at the moment, it requires too many different parts to be completely flexible and work across the routing system. For instance, the following route declarations require a different check in the macro. Tests pass, but it feels relatively messy so far.

```php
Route::blacklist()->get('/home', function () { return ''; })->name('posts.index');
Route::blacklist()->name('posts.show')->get('/posts/{post}', function () { return ''; });
Route::blacklist()->group(['foo' => 'bar'], function () { ... });
```

In saying that it doesn't fully work on the new fluent-style attributes for groups (prefix, domain, middleware and namespace). These return the RouteRegistrar class which has a whitelist of allowed attributes that can be assigned to "about to be created" route instance.

I'm beginning to think that extending the Router would be the simplest and most straightforward solution to add a simple black/white-list flag.

**Comment by DanielCoulbourne** [comment]
@dbonner1987 Could you open a PR to this repo but just add `[WIP]` to the name so I know it's in progress? That way I can look over a diff and we can keep discussion inside this repo so other contributors can get involved?

Thanks so much!
-DC

**Comment by dbonner1987** [comment]
Sounds like a plan. Will get it done tomorrow – calling it a night.

Cheers.
