### ISSUE TITLE
Remove default parameters or setup babel?

### ISSUE THREAD

**Issue by zackify** [tightenco/ziggy#46]
https://github.com/tightenco/ziggy/blob/8962ad96cda7daedd76bf9268861112b613d6063/src/js/route.js#L1 

[Default params](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Default_parameters) only work in modern browsers. For this to work in IE 11 or anything else before es6 you might want to use babel, or just remove the default params and add a check at the top of the function? :)

**Comment by ankurk91** [comment]
May be generate a minified version along.

**Comment by mattstauffer** [comment]
That's totally my fault. I'd rather not introduce babel just for this. I'll update. Thanks @zackify!

**Comment by DanielCoulbourne** [comment]
I think we will eventually end up adding Babel as the Javascript becomes more in-depth, but I agree, lets hold off for now.

**Comment by zackify** [comment]
@DanielCoulbourne if you want I could send a pr that adds minimal stuff and a precommit hook that builds it. It's whatev you want bro

**Comment by ankurk91** [comment]
Params still have a default value set to `{}`.

**Comment by mattstauffer** [comment]
uhguhghghghghghgh
thanks totally did not notice lol
