### ISSUE TITLE
Small helper to get current route name in js

### ISSUE THREAD

**Issue by afigienas** [tightenco/ziggy#49]
Would be great to have current route name in javascript. It is helpful, when need to check if current page is

**Comment by DanielCoulbourne** [comment]
This is a great idea. I need to think about the syntax a bit though.

**Comment by calebporzio** [comment]
That would be super handy!

**Comment by calebporzio** [comment]
Or just a function that checks the route name. Like `route()->is('post.show')`

**Comment by DanielCoulbourne** [comment]
Now that we have fluency I think the way to handle this would be 

```javascript
route().current() // returns post.show
route().current('post.show') // returns true
```

I'd accept a PR adding this functionality in a heartbeat, otherwise I'll add it myself later this week.

**Comment by Robert-Hansen** [comment]
@DanielCoulbourne I'm currently trying to work on the route helper i already got the route().current() working it will return the current route you are on so far it seems to work fine but still need to tweak it and make some tests now i just need to make the other feature work with the route().current('posts.index') ;)

**Comment by DanielCoulbourne** [comment]
Awesome! Excited to see it! And thanks!

**Comment by DanielCoulbourne** [comment]
Did you ever finish this implementation @Robert-Hansen ?

**Comment by the94air** [comment]
Very excited to get up and running with this feature.

**Comment by the94air** [comment]
@DanielCoulbourne It has been 2 months. At least can you respond. @DanielCoulbourne Can you do it? Thanks.

> I'd accept a PR adding this functionality in a heartbeat, otherwise I'll add it myself later this week.

**Comment by DanielCoulbourne** [comment]
Yeah I think I can do that. hopefully tomorrow or this weekend. I wanted to see Robert's implementation but if he's too busy I'll try to knock it out tomorrow. It may make sense to wait until after the es6 conversion, which is my main task for tomorrow.

**Comment by the94air** [comment]
Great :+1:

**Comment by DanielCoulbourne** [comment]
Just to keep you aware I wrote a version of this feature that broke in some pretty basic edge cases, so I'm going to harden it up a little later and hopefully get it done before Monday.

**Comment by the94air** [comment]
@DanielCoulbourne For supporting the project I am thinking of making a small docs gh-pages for this package in vanilla ( html css js - not markdown) before the end of hacktoberfest. Are you OK with this?

**Comment by DanielCoulbourne** [comment]
@the94air Done! Docs added to the readme.

**Comment by the94air** [comment]
The docs is ready. https://the94air.github.io/ziggy/

**Comment by the94air** [comment]
Can you create a gh-pages branch so I can make a pull request. Thanks.

**Comment by the94air** [comment]
Hopefully I can make the PR the next weekend.

**Comment by DanielCoulbourne** [comment]
@the94air What do you need me to do?

**Comment by the94air** [comment]
Make a gh-pages branch

**Comment by the94air** [comment]
Make gh-pages branch

**Comment by the94air** [comment]
Just make `gh-pages` branch and I will take care of every thing else. thanks

**Comment by DanielCoulbourne** [comment]
@the94air https://github.com/tightenco/ziggy/tree/gh-pages

thanks!
