### ISSUE TITLE
Update route() method to allow passing an array of route names.

### ISSUE THREAD

**Issue by DanielCoulbourne** [tightenco/ziggy#5]
Eventually we will want to support groups and namespaces more thoroughly.

**Comment by mattstauffer** [comment]
Can you give an example?

**Comment by DanielCoulbourne** [comment]
Ideally I'd like `route(['posts.index', 'comments.index'])` to return `['posts', 'comments']` but I haven't fully worked out how I want to handle arguments for the individual routes if they require them. This is theoretical for now, but I think solving this problem will allow for supporting full resources in the future.

**Comment by mattstauffer** [comment]
Hm. That feels like not the way I would expect it to work? But I guess I don't know what your plans are. :)

**Comment by DanielCoulbourne** [comment]
I've decided against this. Closing.
