### ISSUE TITLE
'composer require' not installing actual 0.3.0

### ISSUE THREAD

**Issue by heisjj** [tightenco/ziggy#58]
I attempted to use the filter groups, but discovered that 'composer require tightenco/ziggy' isn't pulling the same v0.3.0 that is listed on GitHub (it's pulling an earlier version that is listed as 0.3.0). Can you correct this? Thanks!

Side note, in the docs, you say to use @route('author'), but you may want to correct that to @routes('author'), to avoid confusion. 

Thanks a bunch!

**Comment by Robert-Hansen** [comment]
where do you get the 0.3.0 version from? I can only see the 0.2.3 version as the latest

**Comment by heisjj** [comment]
@Robert-Hansen 
https://packagist.org/packages/tightenco/ziggy
and
https://github.com/tightenco/ziggy/releases

**Comment by Robert-Hansen** [comment]
@heisjj  I just downloaded it and the package.json still says 0.2.3 so I guess he didn't update the version so if you have 0.2.3 you are running the latest release

**Comment by DanielCoulbourne** [comment]
The package.json was out of sync with the composer package version. My bad, although nobody will be installing via NPM so not that big of a deal.

The reason you haven't seen a lot of the recent work in the stable version is that I just haven't tagged a release yet. Planning to tag all the recent changes from this week in a 0.3.1 tomorrow.
