### ISSUE TITLE
Refactor Test Suite and Tag v0.4.0

### ISSUE THREAD

**Issue by DanielCoulbourne** [tightenco/ziggy#61]
I'll tag all the recent changes as soon as I get a little refactoring done on the test suite so I have super confidence that everything is working as expected. Probably tomorrow night.

😄

**Comment by JesseLeite** [comment]
Not big enough for 0.4.0?  Major.Minor.Hotfix?  🙂

Also I think the absolute param got broken, but we have no test to cover this: see https://github.com/tightenco/ziggy/pull/57#pullrequestreview-57661810

**Comment by Robert-Hansen** [comment]
@JesseLeite I removed the if(this.absolute) with else, just for testing purposes to see if it did break any of the tests, it didn't break any. I forgot to change it back, so we can just make a new PR to change it back the way it was before, we need to make some test scenarios first to make sure it all works.

**Comment by DanielCoulbourne** [comment]
Haha thanks guys. @JesseLeite Yeah I guess we should just go big or go home and call this a point release.
