### ISSUE TITLE
Not working well with optional route parameter

### ISSUE THREAD

**Issue by pyaesone17** [tightenco/ziggy#62]
Route::get('user/{name?}', function ($name = null) {
    return $name;
});

Here name is optional but route() function ask to put "name?".

**Comment by Robert-Hansen** [comment]
can you show me you javascript code you are trying to use?

**Comment by DanielCoulbourne** [comment]
@pyaesone17 If you are using v0.3.0 (current stable) then optional params are not yet supported. They are supported in the current-dev which should be tagged as a stable release tonight.

**Comment by DanielCoulbourne** [comment]
Closing for now. Please re-open if this wasn't a versioning issue.

**Comment by pyaesone17** [comment]
@DanielCoulbourne Thanks for your response. I will check a new version when release.
