### ISSUE TITLE
Ziggy v0.4.0 & v0.4.1 returns an object instead of string

### ISSUE THREAD

**Issue by the94air** [tightenco/ziggy#69]
I tried Ziggy in Laravel 5.5 and it is returning an object instead of the full URL of the route like so
```javascript
route('admin.articles.index')
```  

```javascript
// laravel 5.4 returns
"http://blog.dev/admin/articles"

// laravel 5.5 returns
{
  "name": "admin.articles.index",
  "urlParams": {},
  "queryParams": {},
  "absolute": true,
  "domain": "http://blog.dev/",
  "url": "admin/articles"
}
```

**Comment by mgsmus** [comment]
Same situation here, returning object instead of string. Also _@routes_ doesn't work without parentheses anymore. I changed from _@routes_ to _@routes_**()** and it works now.

**Comment by the94air** [comment]
This issue is effecting Laravel 5.5. I wish we can solve it as fast as possible. My work all most stopped. I have tons of ajax calls. I am not attended to restore them with static URL ( It's a pain :sob: ). I don't know what to do.

**Comment by stevebauman** [comment]
@mgsmus, I'm using `@routes` annotation with Laravel 5.5 without issue. That's strange?

@the94air Right now you can use a computed property that will automatically call `toString()` for you with the route, for example:

```
computed: {
    indexUrl()
    {
        return route('posts.index'):
    },

    viewUrl(post)
    {
        return route('posts.show', post);
    }
},
```

**Comment by mgsmus** [comment]
Strange indeed. If I use _@routes_ without parentheses, it's just prints _@routes_ in html source. I'm testing on fresh 5.5 installation.

**Comment by stevebauman** [comment]
@mgsmus Though I'm using Ziggy in an upgraded 5.4 application... Hey yet tried with a fresh instance...

Let me debug further...

**Comment by DanielCoulbourne** [comment]
@the94air are you sure this is a laravel issue? I think you may have possibly been using an older version of Ziggy and updated the Ziggy version at the same time you upgraded Laravel.

**Comment by DanielCoulbourne** [comment]
Could all three of you let me know which Ziggy version you are running? @stevebauman @mgsmus @the94air

**Comment by stevebauman** [comment]
@DanielCoulbourne I'm using the most current release (`v0.4.1`).

**Comment by the94air** [comment]
I am using `"tightenco/ziggy": "^0.4.1"` with a fresh Laravel app.

**Comment by the94air** [comment]
The same thing in a fresh Laravel app. but I got the same results using @routes (with and without parentheses) in:  
OS: windows 7
PHP: 7.1.4 ( XAMPP )
Laravel: 5.5.2
Ziggy: 0.4.1

```javascript
> route('post.index')  
{
  "name": "post.index",
  "urlParams": {},
  "queryParams": {},
  "absolute": true,
  "domain": "http://ziggy.dev/",
  "url": "post"
}
```

**Comment by the94air** [comment]
@DanielCoulbourne it will return the normal URL without a problem in all cases. Please check if is returning string or an object. Thanks.

**Comment by the94air** [comment]
@DanielCoulbourne You where right, It is not a Laravel issue

**Comment by ankurk91** [comment]
This has been discussed earlier #64

**Comment by nWidart** [comment]
I've got the same issue here.

**Comment by the94air** [comment]
For now just use Ziggy v0.3.0 . It may take a bit more time to solve.

**Comment by mgsmus** [comment]
I have created the project from scratch. Laravel version 5.5.3 and ziggy is v0.4.1 and eveything seems ok. Don't know what was affecting to blade directive.

**Comment by nWidart** [comment]
hm strange i'm also on latest laravel & ziggy and it's returning the object.

**Comment by mgsmus** [comment]
@nWidart it returns object if I test it like `console.log(route('index'));` but if I use like that:

```
$.get(route('index'), function(res) {
    console.log(res);
});
```
it returns string as expected (@stevebauman [mentioned](https://github.com/tightenco/ziggy/issues/69#issuecomment-327169240)) and I can see the html response in console.

My problem was the blade directive. It wasn't work without parentheses but it works now.

**Comment by the94air** [comment]
@mgsmus Do you have `ziggy.php` config file in your app?

**Comment by DanielCoulbourne** [comment]
Sounds like @mgsmus is fine now?

@the94air I've been on vacation for like a week but i'm back around now. I'd love to work with you to see what your issue is?

**Comment by nWidart** [comment]
I don't see a recent release/commit. Was this fixed?

**Comment by the94air** [comment]
Finally... welcome back. Hope you enjoyed your vacation :smile:.
I have this resources route
```php
Route::prefix('admin')->group(function () {
	Route::resource('courses', 'Management\CoursesController', ['as' => 'management']);
});
```
And in my ajax call I have
```javascript
@routes
var table = $('#datatable').DataTable({
	ajax: route('management.courses.index'),
});
```
Any thing works perfectly in v0.3.0. And it returns
```
http://ziggy.dev/admin/courses
```
But in v0.4.0 & v0.4.1 it returns
```
http://ziggy.dev/admin/admin/courses
```

**Comment by the94air** [comment]
@nWidart No, not yet.

**Comment by DanielCoulbourne** [comment]
@the94air I will try to duplicate that myself later today.

**Comment by the94air** [comment]
Great :+1:

**Comment by DanielCoulbourne** [comment]
I closed it for two reasons:

1) the issue mentioned in the title is not a bug, it is expected behavior
2) the discussion has brought up several more problems, which are not the same as the title.

As soon as I duplicate the bug you mention relating to `http://ziggy.dev/admin/admin/courses`, I'll open another issue for that. As of now I think this discussion is probably confusing to newcomers.

**Comment by DanielCoulbourne** [comment]
@the94air I am thusfar unable to duplicate your issue.

Here's a screenshot of a fresh Laravel install with Ziggy 0.4.1
<img width="1394" alt="screen shot 2017-09-12 at 8 54 56 pm" src="https://user-images.githubusercontent.com/429010/30354785-be11e450-97fc-11e7-9f63-42f587f182ef.png">

**Comment by the94air** [comment]
It's not a Ziggy issue. It's just me being foolish as Datatable it will prepend the URL with `http/ziggy.dev/admin` and ziggy will return `/admin/courses` causing `http/ziggy.dev/admin/admin/courses`
Thanks for help and sorry for wasting your time.

**Comment by DanielCoulbourne** [comment]
Oh makes sense. No problem glad you got it sorted.

**Comment by nWidart** [comment]
Hm so it's normal that the `route()` sometimes returns an object or a string?

**Comment by DanielCoulbourne** [comment]
It always returns an object which extends the String literal.

**Comment by AidasK** [comment]
Objects as urls does not work with angular 1.x too. 
`$http.get(route('index'))` -> request is sent to something like this `{name: ....`
`angular.isString(route('index')) -> false`

**Comment by the94air** [comment]
@AidasK What about `route('index').toString()`? Does it return any thing?

**Comment by AidasK** [comment]
Yes, it returns my route url. This is the solution I am currently using, but it's not short enough.
