### ISSUE TITLE
Routes within a domain group do not work correctly

### ISSUE THREAD

**Issue by xandor** [tightenco/ziggy#74]
## Missing Protocol

When using routes in a domain group, the domain is added by the js route() function, but there is no protocol attached, so the url returned is incorrect.

in web.php

```php
Route::domain('example.org')->group(function() {
	Route::get('/help', function () { 
			return 'help'; 
		})
		->name('help');
});
```

in blade/js

```js
route('help'); 
// returns 'example.org/help' 
//     instead of '//example.org/help' 
//             or 'http://example.org/help'

```

## Missing Port

Another thing is that if Laravel is running under example.org:81 the php route() function adds the :81 to the url, if its the current domain.

If the current URL is 'http://example.org:81/home'

```php
dump(route('help'));
// returns 'http://example.org:81/help'
```

but in JS

```js
route('help'); 
// returns 'example.org/help' 
//     instead of '//example.org:81/help' 
//             or 'http://example.org:81/help'
```

**Comment by DanielCoulbourne** [comment]
Thank you for the excellent bug report!

I will address these soon!

**Comment by DanielCoulbourne** [comment]
Just saw your PR. I’ll review and hopefully merge it this weekend.

**Comment by DanielCoulbourne** [comment]
#75 Should be ready to merge after some minor changes.

**Comment by xandor** [comment]
sorry i am a little bit under load at the moment, maybe can have a look this weekend.

**Comment by xandor** [comment]
Thanks for the merge
