### ISSUE TITLE
align route.js Router object structure with Vue's router.push parameter 

### ISSUE THREAD

**Issue by gandesc** [tightenco/ziggy#77]
First off, awesome package!

As a suggestion, would you consider aligning the structure of the Router object with that of the object parameters that [Vue Router's push method](https://router.vuejs.org/en/essentials/navigation.html) takes (attribute names)?

I realize that ziggy is front-end-framework agnostic, but I would think most developers are using Vue, especially since it's promoted by Laravel and Taylor.

This would make ziggy more consistent with Vue Router, it's aready pretty close.

Thanks!

**Comment by DanielCoulbourne** [comment]
I’ll look into this a bit tomorrow

**Comment by DanielCoulbourne** [comment]
Hey there. Life has been crazy sorry I haven't touched this yet. I'll be around Friday to play ball.

**Comment by DanielCoulbourne** [comment]
I've done a little more looking into this and I don't think we want to restructure the params that much. At this point they are structured to be very close to Laravel's Route helper function and I don't want to sacrifice that to match Vue. Sorry.
