### ISSUE TITLE
Object.assign() is not supported in IE

### ISSUE THREAD

**Issue by squatto** [tightenco/ziggy#79]
I am unable to use Ziggy in IE, due to the [lack of support for Object.assign()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign#Browser_compatibility). When I attempt to use `route()` I get this:

<img width="489" alt="screen shot 2017-10-17 at 9 41 51 pm" src="https://user-images.githubusercontent.com/748444/31700068-11d19e76-b384-11e7-99c6-ea2f1fcca616.png">

This can be solved with a [polyfill](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign#Polyfill), when necessary.

`Object.assign()` is used twice:

* [https://github.com/tightenco/ziggy/blob/master/src/js/route.js#L23](https://github.com/tightenco/ziggy/blob/master/src/js/route.js#L23)
* [https://github.com/tightenco/ziggy/blob/master/src/js/route.js#L50](https://github.com/tightenco/ziggy/blob/master/src/js/route.js#L50)

**Comment by ankurk91** [comment]
I would suggest setting up babel with babel-plugin-transform-object-assign.
No need to setup webpack though, a npm script would be enough that will utilise babel click.

This we can leverage ES6 syntax in source.

**Comment by DanielCoulbourne** [comment]
I am currently working on an ES6 translation and implementing babel. Once I do this I'll implement these polyfills.
