### ISSUE TITLE
route() helper returns object

### ISSUE THREAD

**Issue by Ctaque** [tightenco/ziggy#81]
Hi,
The route helper is returning an object containing the route informations, i'm not able to generate a route. Am I missing something?

ps: I'm using ziggy version 0.4.1.
Iaravel v5.4.36
laravel-mix to compile react assets

**Comment by Ctaque** [comment]
I was missing something.

**Comment by Ghustavh97** [comment]
Would be nice if you told us what you were missing @Ctaque

**Comment by Ctaque** [comment]
I think i was badly using it. Doing 

route('routename')

Generates an url
