### ISSUE TITLE
Security Issue - hide window.namedRoutes

### ISSUE THREAD

**Issue by MoraesGil** [tightenco/ziggy#82]
I really love this package except by security when anyone can view all my routes using 
window.namedRoutes

there one way to improve this security issue?

**Comment by DanielCoulbourne** [comment]
How is this a security issue?

**Comment by DanielCoulbourne** [comment]
I do not believe exposing routes is a security issue. Security should be handled on the server and should not be dependent on an attacker not knowing your routes.

If you still have routes you would like to keep from sending to Ziggy, you can use our optional [route filtering config options](https://github.com/tightenco/ziggy#filtering-routes).
