### ISSUE TITLE
Proposal: lets not pollute global variables 

### ISSUE THREAD

**Issue by ankurk91** [tightenco/ziggy#88]
Hi,

Right now our Router class depends on these global variables
```
namedRoutes
baseUrl
baseProtocol
baseDomain
basePort
```
These variables are global and can be overwritten accidentally.
Recommended approach would be to namespace them, for example
```js
var Ziggy = {
    namedRoutes : [],
    baseUrl:'some-url',
   /* other properties */
};
```
Thanks.

**Comment by DanielCoulbourne** [comment]
Agreed. 👌
