### ISSUE TITLE
API on subdomain

### ISSUE THREAD

**Issue by gizburdt** [tightenco/ziggy#92]
Hi, 

In my app the api is on a subdomain: `api.example.com`. With Ziggy in Vue, the url is outputted as `http://example.com/api.example.com`. Do you maybe have a solution for this?

Thanks :)

**Comment by DanielCoulbourne** [comment]
Hey!

Could you provide your routes file and the way you are using Ziggy within your app?

We DO support subdomains and you can see we are testing the implementation [here](https://github.com/tightenco/ziggy/blob/master/tests/js/test.route.js#L128). I'd love to try to duplicate your bug and get it fixed.

Thanks!

**Comment by gizburdt** [comment]
Hi,

Thanks for the quick reply :)

This is in the RouteServiceProvider:

```
Route::name('api.')
             ->middleware('web') // @TODO: api, 'auth:api'
             ->domain('api.'.config('app.host'))
             ->namespace('App\Http\Api\Controllers')
             ->group(base_path('routes/api.php'));
```

This is in routes/api.php:

```
Route::resource('addresses', 'AddressController', [
    'only' => ['index', 'store', 'update', 'destroy']
]);
```

This will result in (with php artisan route:list):

```
| /addresses                      | api.addresses.store 
| /addresses                      | api.addresses.index 
...
```

In my Vue component I use `route('api.orders.index')`. Th requested url is this one: `http://example.dev/api.example.dev/addresses`.

Is this enough data? Otherwise let me know :)

**Comment by lampard7824** [comment]
I have the same problem, the router couldn't tell it is a domain name or a path without the protocol (http:// or https://) in front.

**Comment by gizburdt** [comment]
Yes, that's my problem too

**Comment by gizburdt** [comment]
I see there is a src/js/UrlBuilder in de master branch. I think this will fix the problem. But this is not yet tagged.

**Comment by chrisbjr** [comment]
Having the same issue with a subdomain configured. It uses the "domain" variable and prepends the baseUrl.

Example:
http://test.dev/api.test.dev/users

**Comment by chrisbjr** [comment]
Acutally, sorry, no - it does not prepend the baseUrl. It only prepends the domain so end result is this:

api.test.dev/users

So when plugging this in the browser, a sample result is this:

`<a href="api.test.dev/users">Test</a>`

Which, when clicked or taken action through the browser, the browser appends the base URL, redirecting it to `http://test.dev/api.test.dev/users`

**Comment by chrisbjr** [comment]
Okay, sorry for flooding the comments - I see that there was a rewrite of `route.js` in 0.4. We were using 0.3.*. Will try and update and see if there are any improvements.

**Comment by chrisbjr** [comment]
The bug is still there in 0.4.* but it looks like UrlBuilder in master branch has fixed this :)

**Comment by gizburdt** [comment]
Yeah, it's fixed in the master branch. The master branch needs to be tagged.

**Comment by DanielCoulbourne** [comment]
Tagged!

**Comment by chrisbjr** [comment]
Much appreciated @DanielCoulbourne

**Comment by gizburdt** [comment]
Thanks :)
