### ISSUE TITLE
Genetare minified version of javascript

### ISSUE THREAD

**Issue by dohisev** [tightenco/ziggy#93]
I noticed that it generates a really big javascript code, I was wondering if it's not possible to generate a minified version for production like webpack does and it would also "protect" a little bit.

**Comment by ankurk91** [comment]
Are you guys talking about this file -
https://github.com/tightenco/ziggy/blob/master/dist/js/route.min.js

**Comment by DanielCoulbourne** [comment]
We are exporting it. I think we just need to use it by default.

**Comment by DanielCoulbourne** [comment]
Addressed by #99

**Comment by the94air** [comment]
I just tried the minified version in my app and it is beautiful. :+1:
