### ISSUE TITLE
Javascript crash in IE

### ISSUE THREAD

**Issue by Rogierownage** [tightenco/ziggy#94]
Ziggy currently does not work in Internet Explorer. The following code causes an error.

vendor/tightenco/ziggy/src/js/route.js
Line 23:
return Object.assign({}, params);

TypeError: Object doesn't support property or method 'assign'

At this link, you can see that Object.assign() is indeed not supported in IE.
https://developer.mozilla.org/nl/docs/Web/JavaScript/Reference/Global_Objects/Object/assign

A possible solution could be to use the polyfill described here. This could be added to the package.
https://developer.mozilla.org/nl/docs/Web/JavaScript/Reference/Global_Objects/Object/assign#Polyfill

I have tested this locally and it works.

**Comment by DanielCoulbourne** [comment]
This should be fixed in 0.5.0

**Comment by Rogierownage** [comment]
Cool, it does indeed work now. Thanks.
