### ISSUE TITLE
Ziggy does not find the id key in object

### ISSUE THREAD

**Issue by lamberttraccard** [tightenco/ziggy#96]
Hi, 

using Ziggy v0.5.0 I have the following error.

<img width="534" alt="capture d ecran 2017-11-12 a 20 28 43" src="https://user-images.githubusercontent.com/4272598/32702490-66362766-c7e8-11e7-964e-a1ebd67bd970.png">

It works fine if I directly pass an id.

**Comment by DanielCoulbourne** [comment]
Thanks I’ll look into this today.

**Comment by DanielCoulbourne** [comment]
@lamberttraccard can you show me the code that caused this error?

**Comment by lamberttraccard** [comment]
@DanielCoulbourne 
<img width="645" alt="capture d ecran 2017-11-16 a 08 38 43" src="https://user-images.githubusercontent.com/4272598/32879277-a12429cc-caa9-11e7-90fa-acffda5d838e.png">

**Comment by ankurk91** [comment]
Some insights -

```php
// routes/web.php
Route::resource(
        'users', 'UserController', ['only' => [
            'index', 'store', 'edit', 'update'
        ]]
    );
```

Ziggy example
```js
route('users.edit',{user:1}).url()
```
Result -
```
"http://app.local/users/1/edit"
```

It does not look for `id` but `user` property because the route requires {user}.
```
$ php artisan route:list | grep users.edit

|        | GET|HEAD  | users/{user}/edit                   | users.edit              | App\Http\Controllers\UserController@edit                               | web,auth,role:admin,can:manage-users,user                 |
```
Notice the **`{user}`** in url

**Comment by lamberttraccard** [comment]
Thanks @ankurk91, yes it's seems that Ziggy doesn't work with route model binding.

**Comment by DanielCoulbourne** [comment]
I know we did support looking up by generic ID at one point. I believe @JesseLeite wrote that.

It may have gotten lost in the big rewrite. I'll go back and look to see if it's there.

**Comment by JesseLeite** [comment]
Yessir 👌 https://github.com/tightenco/ziggy/blob/master/tests/js/test.route.js#L101-L113

**Comment by DanielCoulbourne** [comment]
Yeah that test is passing...
@lamberttraccard if you can give me a combination of a route definition and a Ziggy usage that makes this break, please re-open.

I'd love a failing test

**Comment by avrahamappel** [comment]
@DanielCoulbourne 
I'm having this issue as well.

`route('contracts.revise', {id:1}).url()`

I get

```
Uncaught Error: Ziggy Error: 'contract' key is required for route 'contracts.revise'
```

Route definition:

```
Route::post('contracts/{contract}/revise', 'ContractController@revise')->name('contracts.revise');
```

I don't have anything filtered right now.

**Comment by the94air** [comment]
Try this @avrahamappel 
```javascript
route('contracts.revise', {contract:1}).url()
```

**Comment by avrahamappel** [comment]
I understand, but that was my test case. In reality I'm passing a JavaScript representation of an  Eloquent Model in there, and according to what I understood from the above discussion, Ziggy should be able to find the `id` field in the object.

**Comment by the94air** [comment]
It is not merged yet as @DanielCoulbourne said
>It may have gotten lost in the big rewrite. I'll go back and look to see if it's there.

**Comment by DanielCoulbourne** [comment]
Will do! May be a day or two unfortunately but thanks for the heads up.

**Comment by fridzema** [comment]
I had this error a few times now. 
Make sure that the value you are passing to object is defined!

**Comment by vortechron** [comment]
im currently using https://spatie.be/docs/laravel-query-builder , it would be nice if it support something like this http://site.test/admin/users?filter[id]=1&filter[ref]=31"

my workaround:
```
filter.map((filterValue, index) => {
    filterString = filterString + `&filter[${filterValue[0]}]=${filterValue[1]}`
})

this.$inertia.replace(this.route(
    'users.index', 
    {
        q: query,
    }
) + filterString)
````
